apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: congen

resources:
- ../../../base/stage-4
- congen-secret.yaml

patches:
- path: patches/keycloak-secret-patch.yaml
  target:
    kind: Secret
    name: keycloak-secret
