apiVersion: v1
kind: Secret
metadata:
  name: congen-secret
  namespace: congen
type: Opaque
data:
  PGUSER: cG9zdGdyZXM=
  PGPASSWORD: cG9zdGdyZXM=
  PGDATABASE: Y29uZ2Vu
  PGWRITERHOST: cG9zdGdyZXM=
  PGREADERHOST: cG9zdGdyZXM=
  PGPORT: NTQzMg==
  KEYCLOAK_CLIENT_SECRET: ZHVtbXktY2xpZW50LXNlY3JldA==
  KEYCLOAK_SERVICE_ACCOUNT_PASSWORD: ZHVtbXktc2VydmljZS1hY2NvdW50LXBhc3N3b3Jk