apiVersion: v1
kind: Secret
metadata:
  name: keycloak-secret
  namespace: congen
type: Opaque
data:
  # Local Keycloak database credentials
  KC_DB_USERNAME: a2V5Y2xvYWs=
  KC_DB_PASSWORD: a2V5Y2xvYWs=
  KC_DB: cG9zdGdyZXM=
  KC_DB_URL: amRiYzpwb3N0Z3Jlc3FsOi8vcG9zdGdyZXM6NTQzMi9rZXljbG9haw==
  KC_BOOTSTRAP_ADMIN_USERNAME: YWRtaW5AY29uZ2VuLmNvbQ==  # admin@congen.com
  KC_BOOTSTRAP_ADMIN_PASSWORD: ZHVtbXktYWRtaW4tcGFzc3dvcmQ=
  CONGEN_BACKEND_CLIENT_SECRET: ZHVtbXktY2xpZW50LXNlY3JldA==
  CONGEN_SERVICE_ACCOUNT_USERNAME: ZHVtbXktc2VydmljZS1hY2NvdW50
  CONGEN_SERVICE_ACCOUNT_PASSWORD: ZHVtbXktc2VydmljZS1hY2NvdW50LXBhc3N3b3Jk
