services:
  postgres:
    image: postgres:14.7-bullseye
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: pg_isready -U postgres
      interval: 1s
      timeout: 1s
      retries: 5
  liquibase:
    image: sfat/liquibase:4.11.0
    environment:
      - DEFAULTS_FILE=./changelog/liquibase.properties
      - DB=jdbc:postgresql://postgres:5432/postgres
      - USERNAME=postgres
      - PASSWORD=postgres
      - READY_FILE=migrations_complete
    volumes:
      - ./resources/migrations:/liquibase/changelog
    depends_on:
      postgres:
        condition: service_healthy
    command: >
      bash -xc '
        rm -f '"$$READY_FILE"' &&
        liquibase --defaultsFile='"$$DEFAULTS_FILE"' --url='"$$DB"' --username='"$$USERNAME"' --password='"$$PASSWORD"' validate &&
        liquibase --defaultsFile='"$$DEFAULTS_FILE"'  --url='"$$DB"' --username='"$$USERNAME"' --password='"$$PASSWORD"' --labels="test" update &&
        touch '"$$READY_FILE"' &&
        sleep 5
      '
    healthcheck:
      test: bash -c '[ -e '"READY_FILE"' ]'
      interval: 1s
      retries: 60
