apiVersion: skaffold/v2beta29
kind: Config
metadata:
  name: congen-dev

build:
  artifacts:
  - image: congen
    jib: {}
  local:
    push: false

deploy:
  kubectl:
    flags:
      global:
      - --namespace=congen
    manifests:
      - k8s/overlays/local

portForward:
- resourceType: service
  resourceName: congen
  port: 8080
  localPort: 8080
- resourceType: service
  resourceName: postgres
  port: 5432
  localPort: 5432 