apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: congen-network-policy
spec:
  egress:
  - to:
    - podSelector:
        matchLabels:
          app: postgres
    ports:
    - protocol: TCP
      port: 5432 