// This file is auto-generated by the `update-kc-gen` command. Do not edit it manually.
// Hash: b9cbaed0ed0e22d725d0e572924ed35b65da8151ae5d082e647b3e61e9399bab

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

import { lazy, Suspense, type ReactNode } from 'react';

export type ThemeName = 'congen-keycloak-account-theme';

export const themeNames: ThemeName[] = ['congen-keycloak-account-theme'];

export type KcEnvName = never;

export const kcEnvNames: KcEnvName[] = [];

export const kcEnvDefaults: Record<KcEnvName, string> = {};

/**
 * NOTE: Do not import this type except maybe in your entrypoint.
 * If you need to import the KcContext import it either from src/login/KcContext.ts or src/account/KcContext.ts.
 * Depending on the theme type you are working on.
 */
export type KcContext = import('./account/KcContext').KcContext;

declare global {
  interface Window {
    kcContext?: KcContext;
  }
}

export const KcAccountPage = lazy(() => import('./account/KcPage'));

export function KcPage(props: { kcContext: KcContext; fallback?: ReactNode }) {
  const { kcContext, fallback } = props;
  return (
    <Suspense fallback={fallback}>
      {(() => {
        switch (kcContext.themeType) {
          case 'account':
            return <KcAccountPage kcContext={kcContext} />;
        }
      })()}
    </Suspense>
  );
}

// NOTE: This is a polyfill for `import.meta.env.BASE_URL` as it's not available in Webpack environment.
export const BASE_URL =
  window.kcContext === undefined || process.env.NODE_ENV === 'development'
    ? process.env.PUBLIC_URL === ''
      ? '/'
      : `undefined/`
    : `${kcContext['x-keycloakify'].resourcesPath}/dist/`;
