apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: congen-ingress
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  ingressClassName: nginx
  rules:
  - host: staging.congen.com 