package com.congen.controllers

import com.congen.dal.ProgramDAL
import com.congen.exceptions.NoResultsFoundException
import com.congen.model.Program
import org.slf4j.LoggerFactory
import org.springframework.http.ResponseEntity
import org.springframework.web.bind.annotation.DeleteMapping
import org.springframework.web.bind.annotation.GetMapping
import org.springframework.web.bind.annotation.PatchMapping
import org.springframework.web.bind.annotation.PathVariable
import org.springframework.web.bind.annotation.PostMapping
import org.springframework.web.bind.annotation.RequestMapping
import org.springframework.web.bind.annotation.RequestParam
import org.springframework.web.bind.annotation.RestController
import reactor.core.publisher.Mono

/**
 * REST controller for Program entity operations.
 *
 * This controller provides CRUD operations for workout programs in the Congen API.
 * Programs represent structured workout plans that can be assigned to users and
 * contain multiple programmed workouts.
 *
 * ## Program Entity
 *
 * A program represents a complete workout plan with:
 * - Unique identifier and name
 * - Description of the program
 * - Associated programmed workouts
 * - User assignments and preferences
 *
 * ## Endpoints
 *
 * - `POST /program/` - Create a new program
 * - `GET /program/{id}` - Retrieve a program by ID
 * - `GET /program/` - Retrieve all programs
 * - `PATCH /program/{id}` - Update an existing program
 * - `DELETE /program/{id}` - Delete a program
 *
 * ## Error Handling
 *
 * - **404 Not Found**: When a program with the specified ID doesn't exist
 * - **422 Unprocessable Entity**: When validation fails
 * - **500 Internal Server Error**: When database operations fail
 *
 * @property programDAL Data access layer for program operations
 *
 * @author Congen Development Team
 * @since 1.0.0
 */
@RestController
@RequestMapping("/program")
class ProgramController(
    private val programDAL: ProgramDAL,
) {
    companion object {
        /** Logger instance for this class. */
        private val logger = LoggerFactory.getLogger(ProgramController::class.java)
    }

    /**
     * Creates a new program.
     *
     * This endpoint accepts program parameters and saves it to the database.
     * The program ID is automatically generated by the database. The method
     * returns the created program with the generated ID. New programs start
     * with week number 1 by default and are marked as active. When a new
     * program is created, all other programs for the same user are automatically
     * deactivated to ensure only one active program per user.
     *
     * @param userId The user ID for the program
     * @param name The name of the program
     * @param isActive Whether the program should be active (defaults to true)
     * @return Mono containing the created program with generated ID
     */
    @PostMapping("/")
    fun save(
        @RequestParam("user_id") userId: Int,
        @RequestParam name: String,
        @RequestParam(name = "is_active", defaultValue = "true") isActive: Boolean,
    ): Mono<ResponseEntity<Program>> {
        logger.info("Saving program: {} for user {} with week number 1 and isActive: {}", name, userId, isActive)
        val startingCurrentWeekNumber = 1
        return programDAL.insertProgram(userId, name, startingCurrentWeekNumber, isActive)
            .map { savedProgram ->
                logger.debug("Saved program with id: {}", savedProgram.id)
                ResponseEntity.ok(savedProgram)
            }
            .doOnError { e ->
                logger.error("Error saving program: {} for user {}", name, userId, e)
            }
    }

    /**
     * Retrieves a program by its unique identifier.
     *
     * This endpoint fetches a program from the database using the provided ID.
     * If no program exists with the given ID, a 404 Not Found response is returned.
     *
     * @param id The unique identifier of the program to retrieve
     * @return Mono containing the program if found, or 404 if not found
     */
    @GetMapping("/{id}")
    fun get(
        @PathVariable("id") id: Long,
    ): Mono<ResponseEntity<Program>> {
        return programDAL.selectProgramById(id)
            .map {
                logger.debug("Found program: {}", id)
                ResponseEntity.ok(it)
            }
            .onErrorResume(NoResultsFoundException::class.java) {
                logger.warn("Program not found: {}", id)
                Mono.just(ResponseEntity.notFound().build())
            }
            .doOnError { e ->
                logger.error("Error getting program: {}", id, e)
            }
    }

    /**
     * Retrieves all programs from the database.
     *
     * This endpoint fetches all program records and returns them as a list.
     * If no programs exist, an empty list is returned.
     *
     * @return ResponseEntity containing a list of all programs
     */
    @GetMapping("/")
    fun getAll(): Mono<ResponseEntity<List<Program>>> {
        logger.debug("Getting all programs")
        return programDAL.selectPrograms()
            .map { programs ->
                logger.debug("Found {} programs", programs.size)
                ResponseEntity.ok(programs)
            }
            .doOnError { e ->
                logger.error("Error getting all programs", e)
            }
    }

    /**
     * Retrieves programs for a specific user, optionally filtered by active status.
     *
     * This endpoint fetches programs belonging to the specified user. If isActive
     * is provided, only programs with that active status are returned. If no
     * programs exist, an empty list is returned.
     *
     * @param userId The user ID to filter programs by
     * @param isActive Optional filter for active status. If not provided, returns all programs for the user
     * @return ResponseEntity containing a list of programs for the user
     */
    @GetMapping("/user/{user_id}")
    fun getByUserId(
        @PathVariable("user_id") userId: Int,
        @RequestParam(name = "is_active", required = false) isActive: Boolean? = null,
    ): Mono<ResponseEntity<List<Program>>> {
        logger.debug("Getting programs for user: {} with isActive filter: {}", userId, isActive)
        return programDAL.selectProgramsByUserId(userId, isActive)
            .map { programs ->
                logger.debug("Found {} programs for user: {}", programs.size, userId)
                ResponseEntity.ok(programs)
            }
            .doOnError { e ->
                logger.error("Error getting programs for user: {}", userId, e)
            }
    }

    /**
     * Updates an existing program.
     *
     * This endpoint updates a program with the specified ID using the provided
     * parameters. The ID from the path parameter is used to ensure the correct
     * program is updated. If no program exists with the given ID, a 404 Not Found
     * response is returned.
     *
     * @param id The unique identifier of the program to update
     * @param name The updated name of the program
     * @param currentWeekNumber The updated current week number
     * @param isActive Whether the program should be active
     * @return Mono containing the updated program, or 404 if not found
     */
    @PatchMapping("/{id}")
    fun update(
        @PathVariable("id") id: Long,
        @RequestParam name: String,
        @RequestParam("current_week_number") currentWeekNumber: Int,
        @RequestParam("is_active") isActive: Boolean,
    ): Mono<ResponseEntity<Program>> {
        return programDAL.updateProgram(id, name, currentWeekNumber, isActive)
            .map {
                logger.debug("Updated program: {}", id)
                ResponseEntity.ok(it)
            }
            .onErrorResume(NoResultsFoundException::class.java) {
                logger.warn("Program not found for update: {}", id)
                Mono.just(ResponseEntity.notFound().build())
            }
            .doOnError { e ->
                logger.error("Error updating program: {}", id, e)
            }
    }

    /**
     * Deletes a program by its unique identifier.
     *
     * This endpoint removes a program from the database using the provided ID.
     * If no program exists with the given ID, a 404 Not Found response is returned.
     * The method returns the deleted program data for confirmation.
     *
     * @param id The unique identifier of the program to delete
     * @return Mono containing the deleted program, or 404 if not found
     */
    @DeleteMapping("/{id}")
    fun delete(
        @PathVariable("id") id: Long,
    ): Mono<ResponseEntity<Program>> {
        return programDAL.deleteProgram(id)
            .map {
                logger.debug("Deleted program: {}", id)
                ResponseEntity.ok(it)
            }
            .onErrorResume(NoResultsFoundException::class.java) {
                logger.warn("Program not found for deletion: {}", id)
                Mono.just(ResponseEntity.notFound().build())
            }
            .doOnError { e ->
                logger.error("Error deleting program: {}", id, e)
            }
    }
}
