package com.congen.controllers

import com.congen.model.ProgrammedWorkout
import com.congen.service.GdprComplianceService
import com.congen.service.ProgramService
import com.congen.service.ProgrammedWorkoutService
import com.congen.util.KeycloakUtil
import org.slf4j.LoggerFactory
import org.springframework.http.ResponseEntity
import org.springframework.security.access.AccessDeniedException
import org.springframework.security.access.prepost.PreAuthorize
import org.springframework.web.bind.annotation.DeleteMapping
import org.springframework.web.bind.annotation.GetMapping
import org.springframework.web.bind.annotation.PatchMapping
import org.springframework.web.bind.annotation.PathVariable
import org.springframework.web.bind.annotation.PostMapping
import org.springframework.web.bind.annotation.RequestMapping
import org.springframework.web.bind.annotation.RequestParam
import org.springframework.web.bind.annotation.RestController
import reactor.core.publisher.Flux
import reactor.core.publisher.Mono

/**
 * REST controller for ProgrammedWorkout entity operations.
 *
 * This controller provides CRUD operations for programmed workouts in the Congen API.
 * Programmed workouts represent specific workout sessions within a program, with
 * their own day number and associated workout stages.
 *
 * ## ProgrammedWorkout Entity
 *
 * A programmed workout represents a specific workout session within a program:
 * - Unique identifier and name
 * - Reference to the parent program
 * - Day number within the program
 * - Associated workout stages
 *
 * ## Endpoints
 *
 * - `POST /programmed_workout/` - Create a new programmed workout
 * - `GET /programmed_workout/{id}` - Retrieve a programmed workout by ID
 * - `GET /programmed_workout/` - Retrieve all programmed workouts
 * - `GET /programmed_workout/program/{programId}` - Get workouts for a specific program
 * - `PATCH /programmed_workout/{id}` - Update an existing programmed workout
 * - `DELETE /programmed_workout/{id}` - Delete a programmed workout
 *
 * ## Error Handling
 *
 * - **404 Not Found**: When a programmed workout with the specified ID doesn't exist
 * - **422 Unprocessable Entity**: When validation fails
 * - **500 Internal Server Error**: When database operations fail
 *
 * @param programmedWorkoutService Service for programmed workout operations
 * @param programService Service for program operations
 * @param keycloakUtil Utility for Keycloak operations
 * @param gdprComplianceService Service for GDPR compliance operations
 *
 * @author Congen Development Team
 * @since 1.0.0
 */
@RestController
@RequestMapping("/programmed_workout")
class ProgrammedWorkoutController(
    private val programmedWorkoutService: ProgrammedWorkoutService,
    private val programService: ProgramService,
    private val keycloakUtil: KeycloakUtil,
    private val gdprComplianceService: GdprComplianceService
) {
    companion object {
        /** Logger instance for this class. */
        private val logger = LoggerFactory.getLogger(ProgrammedWorkoutController::class.java)
    }

    /**
     * Creates a new programmed workout.
     *
     * This endpoint accepts programmed workout parameters and saves it to the database.
     * The programmed workout ID is automatically generated by the database. The method
     * returns the created programmed workout with the generated ID.
     *
     * @param programId The ID of the program this workout belongs to
     * @param dayNumber The day number within the program
     * @param name The name of the workout
     * @return Mono containing the created programmed workout with generated ID
     */
    @PostMapping("/")
    @PreAuthorize("isAuthenticated()")
    fun save(
        @RequestParam("program_id") programId: Long,
        @RequestParam("day_number") dayNumber: Int,
        @RequestParam name: String,
    ): Mono<ResponseEntity<ProgrammedWorkout>> {
        return keycloakUtil.getCurrentUserId().zipWith(keycloakUtil.getCurrentUserRoles()) { userId, roles ->
            Pair(userId, roles)
        }.flatMap { (userId, roles) ->
            val isAdminOrService = roles.contains("admin") || roles.contains("service")
            programService.isOwner(programId, userId).flatMap { isOwner ->
                if (isAdminOrService || isOwner) {
                    val consentUserIdMono =
                        if (isAdminOrService) {
                            programService.getOwner(programId)
                        } else {
                            Mono.just(userId)
                        }
                    consentUserIdMono.flatMap { ownerId ->
                        gdprComplianceService.withUserConsent(ownerId) {
                            programmedWorkoutService.insertProgrammedWorkout(programId, dayNumber, name)
                                .map {
                                    logger.debug("Saved programmed workout with id: {}", it.id)
                                    ResponseEntity.ok(it)
                                }
                                .doOnError { e ->
                                    logger.error("Error saving programmed workout: {} for program {}", name, programId, e)
                                }
                        }
                    }
                } else {
                    Mono.error(AccessDeniedException("Access denied: User is not the owner of this program"))
                }
            }
        }
    }

    /**
     * Retrieves a programmed workout by its unique identifier.
     *
     * This endpoint fetches a programmed workout from the database using the provided ID.
     * If no programmed workout exists with the given ID, a 404 Not Found response is returned.
     *
     * @param id The unique identifier of the programmed workout to retrieve
     * @return Mono containing the programmed workout if found, or 404 if not found
     */
    @GetMapping("/{id}")
    @PreAuthorize("isAuthenticated()")
    fun get(
        @PathVariable("id") id: Long,
    ): Mono<ResponseEntity<ProgrammedWorkout>> {
        return keycloakUtil.getCurrentUserId().zipWith(keycloakUtil.getCurrentUserRoles())
            .flatMap { tuple ->
                val userId = tuple.t1
                val roles = tuple.t2
                val isAdminOrService = roles.contains("admin") || roles.contains("service")

                // First check if the programmed workout exists
                programmedWorkoutService.selectProgrammedWorkoutById(id)
                    .flatMap { programmedWorkout ->
                        // Programmed workout exists, now check ownership
                        programmedWorkoutService.isOwner(id, userId).flatMap { isOwner ->
                            if (isAdminOrService || isOwner) {
                                val consentUserIdMono =
                                    if (isAdminOrService) {
                                        programmedWorkoutService.getOwner(id)
                                    } else {
                                        Mono.just(userId)
                                    }
                                consentUserIdMono.flatMap { ownerId ->
                                    gdprComplianceService.withUserConsent(ownerId) {
                                        Mono.just(ResponseEntity.ok(programmedWorkout))
                                    }
                                }
                            } else {
                                Mono.error(AccessDeniedException("Access denied: User is not the owner of this programmed workout"))
                            }
                        }
                    }
                    .doOnError { e ->
                        logger.error("Error getting programmed workout: {}", id, e)
                    }
            }
    }

    /**
     * Retrieves all programmed workouts from the database.
     *
     * This endpoint fetches all programmed workout records and returns them as a list.
     * If no programmed workouts exist, an empty list is returned.
     *
     * @return ResponseEntity containing a list of all programmed workouts
     */
    @GetMapping("/")
    @PreAuthorize("isAuthenticated()")
    fun getAll(): Mono<ResponseEntity<List<ProgrammedWorkout>>> {
        return keycloakUtil.getCurrentUserId().zipWith(keycloakUtil.getCurrentUserRoles()).flatMap { tuple ->
            val userId = tuple.t1
            val roles = tuple.t2
            val isAdminOrService = roles.contains("admin") || roles.contains("service")
            if (isAdminOrService) {
                programmedWorkoutService.selectProgrammedWorkouts()
                    .flatMap { programmedWorkouts ->
                        Flux.fromIterable(programmedWorkouts)
                            .flatMap { programmedWorkout ->
                                programmedWorkoutService.getOwner(programmedWorkout.id)
                                    .flatMap { ownerId ->
                                        gdprComplianceService.hasUserConsent(ownerId)
                                            .filter { hasConsent -> hasConsent }
                                            .map { programmedWorkout }
                                    }
                            }
                            .collectList()
                    }
                    .map { programmedWorkouts -> ResponseEntity.ok(programmedWorkouts) }
            } else {
                gdprComplianceService.withUserConsent(userId) {
                    programmedWorkoutService.selectProgrammedWorkoutsByUserId(userId)
                        .map { programmedWorkouts -> ResponseEntity.ok(programmedWorkouts) }
                }
            }
        }
    }

    /**
     * Retrieves all programmed workouts for a specific program.
     *
     * This endpoint fetches all programmed workouts that belong to a specific
     * program, ordered by their day number within the program.
     * Optionally filters by week number if provided.
     *
     * @param programId The unique identifier of the program
     * @param week Optional week number to filter workouts (1-based)
     * @return ResponseEntity containing a list of programmed workouts for the program
     */
    @GetMapping("/program/{program_id}")
    @PreAuthorize("isAuthenticated()")
    fun getByProgramId(
        @PathVariable("program_id") programId: Long,
        @RequestParam("week", required = false) week: Int? = null,
    ): Mono<ResponseEntity<List<ProgrammedWorkout>>> {
        return keycloakUtil.getCurrentUserId().zipWith(keycloakUtil.getCurrentUserRoles()) { userId, roles ->
            Pair(userId, roles)
        }.flatMap { (userId, roles) ->
            val isAdminOrService = roles.contains("admin") || roles.contains("service")
            programService.isOwner(programId, userId).flatMap { isOwner ->
                if (isAdminOrService || isOwner) {
                    val consentUserIdMono =
                        if (isAdminOrService) {
                            programService.getOwner(programId)
                        } else {
                            Mono.just(userId)
                        }
                    consentUserIdMono.flatMap { ownerId ->
                        gdprComplianceService.withUserConsent(ownerId) {
                            val workoutMono = if (week != null) {
                                // Validate week number
                                if (week < 1) {
                                    Mono.error(IllegalArgumentException("Week number must be at least 1, got: $week"))
                                } else {
                                    programmedWorkoutService.selectProgrammedWorkoutsByProgramId(programId, week)
                                }
                            } else {
                                programmedWorkoutService.selectProgrammedWorkoutsByProgramId(programId)
                            }
                            
                            workoutMono.map { programmedWorkouts ->
                                val weekDescription = if (week != null) " for week $week" else ""
                                logger.debug("Found {} programmed workouts for program: {}{}", programmedWorkouts.size, programId, weekDescription)
                                ResponseEntity.ok(programmedWorkouts)
                            }
                            .doOnError { e ->
                                logger.error("Error getting programmed workouts for program: {}", programId, e)
                            }
                        }
                    }
                } else {
                    Mono.error(AccessDeniedException("Access denied: User is not the owner of this program"))
                }
            }
        }
    }

    /**
     * Updates an existing programmed workout.
     *
     * This endpoint updates a programmed workout using the provided parameters.
     * The programmed workout ID from the path parameter is used to identify which workout
     * to update.
     *
     * @param id The unique identifier of the programmed workout to update
     * @param programId The updated program ID
     * @param dayNumber The updated day number within the program
     * @param name The updated name of the workout
     * @return ResponseEntity containing the updated programmed workout
     */
    @PatchMapping("/{id}")
    @PreAuthorize("isAuthenticated()")
    fun update(
        @PathVariable("id") id: Long,
        @RequestParam("program_id") programId: Long,
        @RequestParam("day_number") dayNumber: Int,
        @RequestParam name: String,
    ): Mono<ResponseEntity<ProgrammedWorkout>> {
        return keycloakUtil.getCurrentUserId().zipWith(keycloakUtil.getCurrentUserRoles()) { userId, roles ->
            Pair(userId, roles)
        }.flatMap { (userId, roles) ->
            val isAdminOrService = roles.contains("admin") || roles.contains("service")
            programService.isOwner(
                programId,
                userId
            ).zipWith(programmedWorkoutService.isOwner(id, userId)) { isProgramOwner, isWorkoutOwner ->
                isProgramOwner && isWorkoutOwner
            }.flatMap { hasAccess ->
                if (isAdminOrService || hasAccess) {
                    val consentUserIdMono =
                        if (isAdminOrService) {
                            programmedWorkoutService.getOwner(id)
                        } else {
                            Mono.just(userId)
                        }
                    consentUserIdMono.flatMap { ownerId ->
                        gdprComplianceService.withUserConsent(ownerId) {
                            programmedWorkoutService.updateProgrammedWorkout(id, programId, dayNumber, name)
                                .map {
                                    logger.debug("Updated programmed workout: {}", id)
                                    ResponseEntity.ok(it)
                                }
                                .doOnError { e ->
                                    logger.error("Error updating programmed workout: {}", id, e)
                                }
                        }
                    }
                } else {
                    Mono.error(AccessDeniedException("Access denied: User is not the owner of this program and programmed workout"))
                }
            }
        }
    }

    /**
     * Deletes a programmed workout by its unique identifier.
     *
     * This endpoint removes a programmed workout from the database using the provided ID.
     * The method returns the deleted programmed workout data for confirmation.
     *
     * @param id The unique identifier of the programmed workout to delete
     * @return ResponseEntity containing the deleted programmed workout
     */
    @DeleteMapping("/{id}")
    @PreAuthorize("isAuthenticated()")
    fun delete(
        @PathVariable("id") id: Long,
    ): Mono<ResponseEntity<ProgrammedWorkout>> {
        return keycloakUtil.getCurrentUserId().zipWith(keycloakUtil.getCurrentUserRoles()) { userId, roles ->
            Pair(userId, roles)
        }.flatMap { (userId, roles) ->
            val isAdminOrService = roles.contains("admin") || roles.contains("service")
            programmedWorkoutService.isOwner(id, userId).flatMap { isOwner ->
                if (isAdminOrService || isOwner) {
                    val consentUserIdMono =
                        if (isAdminOrService) {
                            programmedWorkoutService.getOwner(id)
                        } else {
                            Mono.just(userId)
                        }
                    consentUserIdMono.flatMap { ownerId ->
                        gdprComplianceService.withUserConsent(ownerId) {
                            programmedWorkoutService.deleteProgrammedWorkout(id)
                                .map {
                                    logger.debug("Deleted programmed workout: {}", id)
                                    ResponseEntity.ok(it)
                                }
                                .doOnError { e ->
                                    logger.error("Error deleting programmed workout: {}", id, e)
                                }
                        }
                    }
                } else {
                    Mono.error(AccessDeniedException("Access denied: User is not the owner of this programmed workout"))
                }
            }
        }
    }
}
