package com.congen.controllers

import com.congen.model.Program
import com.congen.service.GdprComplianceService
import com.congen.service.ProgramService
import com.congen.util.KeycloakUtil
import reactor.core.publisher.Flux
import io.swagger.v3.oas.annotations.Operation
import io.swagger.v3.oas.annotations.Parameter
import io.swagger.v3.oas.annotations.media.Content
import io.swagger.v3.oas.annotations.responses.ApiResponse
import io.swagger.v3.oas.annotations.responses.ApiResponses
import org.slf4j.LoggerFactory
import org.springframework.http.ResponseEntity
import org.springframework.security.access.AccessDeniedException
import org.springframework.security.access.prepost.PreAuthorize
import org.springframework.web.bind.annotation.DeleteMapping
import org.springframework.web.bind.annotation.GetMapping
import org.springframework.web.bind.annotation.PatchMapping
import org.springframework.web.bind.annotation.PathVariable
import org.springframework.web.bind.annotation.PostMapping
import org.springframework.web.bind.annotation.RequestMapping
import org.springframework.web.bind.annotation.RequestParam
import org.springframework.web.bind.annotation.RestController
import reactor.core.publisher.Mono

/**
 * REST controller for Program entity operations.
 *
 * This controller provides CRUD operations for workout programs in the Congen API.
 * Programs represent structured workout plans that can be assigned to users and
 * contain multiple programmed workouts.
 *
 * ## Program Entity
 *
 * A program represents a complete workout plan with:
 * - Unique identifier and name
 * - Description of the program
 * - Associated programmed workouts
 * - User assignments and preferences
 *
 * ## Endpoints
 *
 * - `POST /program/` - Create a new program
 * - `GET /program/{id}` - Retrieve a program by ID
 * - `GET /program/` - Retrieve all programs
 * - `PATCH /program/{id}` - Update an existing program
 * - `DELETE /program/{id}` - Delete a program
 *
 * ## Error Handling
 *
 * - **404 Not Found**: When a program with the specified ID doesn't exist
 * - **422 Unprocessable Entity**: When validation fails
 * - **500 Internal Server Error**: When database operations fail
 *
 * @property programDAL Data access layer for program operations
 *
 * @author Congen Development Team
 * @since 1.0.0
 */
@RestController
@RequestMapping("/program")
class ProgramController(
    private val programService: ProgramService,
    private val keycloakUtil: KeycloakUtil,
    private val gdprComplianceService: GdprComplianceService
) {
    companion object {
        /** Logger instance for this class. */
        private val logger = LoggerFactory.getLogger(ProgramController::class.java)
    }

    /**
     * Creates a new program.
     *
     * This endpoint accepts program parameters and saves it to the database.
     * The program ID is automatically generated by the database. The method
     * returns the created program with the generated ID. New programs start
     * with week number 1 by default and are marked as active. When a new
     * program is created, all other programs for the same user are automatically
     * deactivated to ensure only one active program per user.
     *
     * @param userId The Keycloak user ID for the program
     * @param name The name of the program
     * @param isActive Whether the program should be active (defaults to true)
     * @return Mono containing the created program with generated ID
     */
    @PostMapping("/")
    @PreAuthorize("hasRole('admin') or hasRole('service') or #userId == principal.subject")
    @Operation(
        summary = "Create program",
        description = "Creates a new program for a user.",
    )
    @ApiResponses(
        value = [
            ApiResponse(
                responseCode = "200",
                description = "Program created successfully",
                content = [Content(mediaType = "application/json")],
            ),
        ],
    )
    fun save(
        @RequestParam("user_id") userId: String,
        @RequestParam name: String,
        @RequestParam(name = "is_active", defaultValue = "true") isActive: Boolean,
    ): Mono<ResponseEntity<Program>> {
        return keycloakUtil.getCurrentUserId().flatMap { keycloakId ->
            keycloakUtil.getCurrentUserRoles().flatMap { roles ->
                if (roles.contains("admin") || roles.contains("service") || userId == keycloakId) {
                    val consentUserIdMono = if (roles.contains("admin") || roles.contains("service")) {
                        Mono.just(userId)
                    } else {
                        Mono.just(keycloakId)
                    }
                    consentUserIdMono.flatMap { ownerId ->
                        gdprComplianceService.withUserConsent(ownerId) {
                            logger.info("Saving program: {} for user {} with week number 1 and isActive: {}", name, userId, isActive)
                            val startingCurrentWeekNumber = 1
                            programService.insertProgram(userId, name, startingCurrentWeekNumber, isActive)
                                .map { savedProgram ->
                                    logger.debug("Saved program with id: {}", savedProgram.id)
                                    ResponseEntity.ok(savedProgram)
                                }
                        }
                    }
                } else {
                    Mono.error(AccessDeniedException("User not authorized to create programs for other users"))
                }
            }
        }
    }

    /**
     * Retrieves a program by its unique identifier.
     *
     * This endpoint fetches a program from the database using the provided ID.
     * If no program exists with the given ID, a 404 Not Found response is returned.
     *
     * @param id The unique identifier of the program to retrieve
     * @return Mono containing the program if found, or 404 if not found
     */
    @GetMapping("/{id}")
    @PreAuthorize("isAuthenticated()")
    @Operation(
        summary = "Get program by ID",
        description = "Retrieves a specific program by its unique identifier.",
    )
    @ApiResponses(
        value = [
            ApiResponse(
                responseCode = "200",
                description = "Program found successfully",
                content = [Content(mediaType = "application/json")],
            ),
            ApiResponse(
                responseCode = "404",
                description = "Program not found",
                content = [Content(mediaType = "application/json")],
            ),
        ],
    )
    fun get(
        @Parameter(
            description = "Unique identifier of the program",
            required = true,
            example = "1",
        )
        @PathVariable("id") id: Long,
    ): Mono<ResponseEntity<Program>> {
        return keycloakUtil.getCurrentUserId().zipWith(keycloakUtil.getCurrentUserRoles()) { userId, roles ->
            Pair(userId, roles)
        }.flatMap { (userId, roles) ->
            val isAdminOrService = roles.contains("admin") || roles.contains("service")
            programService.selectProgramById(id)
                .flatMap { program ->
                    val hasAccess = isAdminOrService || program.userId == userId
                    if (hasAccess) {
                        val consentUserIdMono = if (isAdminOrService) {
                            Mono.just(program.userId)
                        } else {
                            Mono.just(userId)
                        }
                        consentUserIdMono.flatMap { ownerId ->
                            gdprComplianceService.withUserConsent(ownerId) {
                                Mono.just(program)
                                    .map {
                                        logger.debug("Found program: {}", id)
                                        ResponseEntity.ok(it)
                                    }
                            }
                        }
                    } else {
                        Mono.error(AccessDeniedException("Access denied: User is not the owner of this program"))
                    }
                }
        }
    }

    /**
     * Retrieves all programs from the database.
     *
     * This endpoint fetches all program records and returns them as a list.
     * If no programs exist, an empty list is returned.
     *
     * @return ResponseEntity containing a list of all programs
     */
    @GetMapping("/")
    @PreAuthorize("isAuthenticated()")
    @Operation(
        summary = "Get all programs",
        description = "Retrieves a list of all programs.",
    )
    @ApiResponses(
        value = [
            ApiResponse(
                responseCode = "200",
                description = "Programs retrieved successfully",
                content = [Content(mediaType = "application/json")],
            ),
        ],
    )
    fun getAll(): Mono<ResponseEntity<List<Program>>> {
        return keycloakUtil.getCurrentUserId().zipWith(keycloakUtil.getCurrentUserRoles()) { userId, roles ->
            Pair(userId, roles)
        }.flatMap { (userId, roles) ->
            val isAdminOrService = roles.contains("admin") || roles.contains("service")
            if (isAdminOrService) {
                programService.selectPrograms()
                    .flatMap { programs ->
                        Flux.fromIterable(programs)
                            .flatMap { program ->
                                gdprComplianceService.hasUserConsent(program.userId)
                                    .filter { hasConsent -> hasConsent }
                                    .map { program }
                            }
                            .collectList()
                    }
                    .map { programs -> ResponseEntity.ok(programs) }
            } else {
                gdprComplianceService.withUserConsent(userId) {
                    programService.selectProgramsByUserId(userId, null)
                        .map { programs -> ResponseEntity.ok(programs) }
                }
            }
        }
    }

    /**
     * Retrieves programs for a specific user, optionally filtered by active status.
     *
     * This endpoint fetches programs belonging to the specified user. If isActive
     * is provided, only programs with that active status are returned. If no
     * programs exist, an empty list is returned.
     *
     * @param userId The Keycloak user ID to filter programs by
     * @param isActive Optional filter for active status. If not provided, returns all programs for the user
     * @return ResponseEntity containing a list of programs for the user
     */
    @GetMapping("/user/{user_id}")
    @PreAuthorize("hasRole('admin') or hasRole('service') or #userId == principal.subject")
    @Operation(
        summary = "Get programs by user ID",
        description = "Retrieves programs for a specific user, optionally filtered by active status.",
    )
    @ApiResponses(
        value = [
            ApiResponse(
                responseCode = "200",
                description = "Programs retrieved successfully",
                content = [Content(mediaType = "application/json")],
            ),
        ],
    )
    fun getByUserId(
        @Parameter(
            description = "Keycloak user ID to filter programs by",
            required = true,
            example = "b226d772-c063-4974-ae08-ab64134abbcf",
        )
        @PathVariable("user_id") userId: String,
        @Parameter(
            description = "Optional filter for active status",
            required = false,
            example = "true",
        )
        @RequestParam(name = "is_active", required = false) isActive: Boolean? = null,
    ): Mono<ResponseEntity<List<Program>>> {
        logger.debug("Getting programs for user: {} with isActive filter: {}", userId, isActive)
        return programService.selectProgramsByUserId(userId, isActive)
            .map { programs ->
                logger.debug("Found {} programs for user: {}", programs.size, userId)
                ResponseEntity.ok(programs)
            }
    }

    /**
     * Updates an existing program.
     *
     * This endpoint updates a program with the specified ID using the provided
     * parameters. The ID from the path parameter is used to ensure the correct
     * program is updated. If no program exists with the given ID, a 404 Not Found
     * response is returned.
     *
     * @param id The unique identifier of the program to update
     * @param name The updated name of the program
     * @param currentWeekNumber The updated current week number
     * @param isActive Whether the program should be active
     * @return Mono containing the updated program, or 404 if not found
     */
    @PatchMapping("/{id}")
    @PreAuthorize("isAuthenticated()")
    @Operation(
        summary = "Update program",
        description = "Updates an existing program with the specified ID.",
    )
    @ApiResponses(
        value = [
            ApiResponse(
                responseCode = "200",
                description = "Program updated successfully",
                content = [Content(mediaType = "application/json")],
            ),
            ApiResponse(
                responseCode = "404",
                description = "Program not found",
                content = [Content(mediaType = "application/json")],
            ),
        ],
    )
    fun update(
        @Parameter(
            description = "Unique identifier of the program to update",
            required = true,
            example = "1",
        )
        @PathVariable("id") id: Long,
        @Parameter(
            description = "Updated name of the program",
            required = true,
            example = "Updated Program Name",
        )
        @RequestParam name: String,
        @Parameter(
            description = "Updated current week number",
            required = true,
            example = "2",
        )
        @RequestParam("current_week_number") currentWeekNumber: Int,
        @Parameter(
            description = "Whether the program should be active",
            required = true,
            example = "true",
        )
        @RequestParam("is_active") isActive: Boolean,
    ): Mono<ResponseEntity<Program>> {
        return keycloakUtil.getCurrentUserId().zipWith(keycloakUtil.getCurrentUserRoles()) { userId, roles ->
            Pair(userId, roles)
        }.flatMap { (userId, roles) ->
            val isAdminOrService = roles.contains("admin") || roles.contains("service")
            programService.selectProgramById(id)
                .flatMap { program ->
                    val hasAccess = isAdminOrService || program.userId == userId
                    if (hasAccess) {
                        val consentUserIdMono = if (isAdminOrService) {
                            Mono.just(program.userId)
                        } else {
                            Mono.just(userId)
                        }
                        consentUserIdMono.flatMap { ownerId ->
                            gdprComplianceService.withUserConsent(ownerId) {
                                programService.updateProgram(id, name, currentWeekNumber, isActive)
                                    .map {
                                        logger.debug("Updated program: {}", id)
                                        ResponseEntity.ok(it)
                                    }
                            }
                        }
                    } else {
                        Mono.error(AccessDeniedException("Access denied: User is not the owner of this program"))
                    }
                }
        }
    }

    /**
     * Deletes a program by its unique identifier.
     *
     * This endpoint removes a program from the database using the provided ID.
     * If no program exists with the given ID, a 404 Not Found response is returned.
     * The method returns the deleted program data for confirmation.
     *
     * @param id The unique identifier of the program to delete
     * @return Mono containing the deleted program, or 404 if not found
     */
    @DeleteMapping("/{id}")
    @PreAuthorize("isAuthenticated()")
    @Operation(
        summary = "Delete program",
        description = "Deletes a program by its unique identifier.",
    )
    @ApiResponses(
        value = [
            ApiResponse(
                responseCode = "200",
                description = "Program deleted successfully",
                content = [Content(mediaType = "application/json")],
            ),
            ApiResponse(
                responseCode = "404",
                description = "Program not found",
                content = [Content(mediaType = "application/json")],
            ),
        ],
    )
    fun delete(
        @Parameter(
            description = "Unique identifier of the program to delete",
            required = true,
            example = "1",
        )
        @PathVariable("id") id: Long,
    ): Mono<ResponseEntity<Program>> {
        return keycloakUtil.getCurrentUserId().zipWith(keycloakUtil.getCurrentUserRoles()) { userId, roles ->
            Pair(userId, roles)
        }.flatMap { (userId, roles) ->
            val isAdminOrService = roles.contains("admin") || roles.contains("service")
            programService.selectProgramById(id)
                .flatMap { program ->
                    val hasAccess = isAdminOrService || program.userId == userId
                    if (hasAccess) {
                        val consentUserIdMono = if (isAdminOrService) {
                            Mono.just(program.userId)
                        } else {
                            Mono.just(userId)
                        }
                        consentUserIdMono.flatMap { ownerId ->
                            gdprComplianceService.withUserConsent(ownerId) {
                                programService.deleteProgram(id)
                                    .map {
                                        logger.debug("Deleted program: {}", id)
                                        ResponseEntity.ok(it)
                                    }
                            }
                        }
                    } else {
                        Mono.error(AccessDeniedException("Access denied: User is not the owner of this program"))
                    }
                }
        }
    }
}
