package com.congen.controllers

import com.congen.model.ProgrammedExercise
import com.congen.service.GdprComplianceService
import com.congen.service.ProgrammedExerciseService
import com.congen.service.WorkoutStageService
import com.congen.util.KeycloakUtil
import reactor.core.publisher.Flux
import org.slf4j.LoggerFactory
import org.springframework.http.ResponseEntity
import org.springframework.security.access.AccessDeniedException
import org.springframework.security.access.prepost.PreAuthorize
import org.springframework.web.bind.annotation.DeleteMapping
import org.springframework.web.bind.annotation.GetMapping
import org.springframework.web.bind.annotation.PatchMapping
import org.springframework.web.bind.annotation.PathVariable
import org.springframework.web.bind.annotation.PostMapping
import org.springframework.web.bind.annotation.RequestMapping
import org.springframework.web.bind.annotation.RequestParam
import org.springframework.web.bind.annotation.RestController
import reactor.core.publisher.Mono

/**
 * REST controller for ProgrammedExercise entity operations.
 *
 * This controller provides CRUD operations for programmed exercises in the Congen API.
 * Programmed exercises represent specific exercises that are assigned to workout stages
 * within a programmed workout, with their own configuration and set schemes.
 *
 * ## ProgrammedExercise Entity
 *
 * A programmed exercise represents an exercise within a workout stage:
 * - Unique identifier and position within the stage
 * - Reference to the parent workout stage
 * - Exercise name and configuration
 * - Associated set schemes for the exercise
 *
 * ## Endpoints
 *
 * - `POST /programmed_exercise/` - Create a new programmed exercise
 * - `GET /programmed_exercise/{id}` - Retrieve a programmed exercise by ID
 * - `GET /programmed_exercise/stage/{workoutStageId}` - Get exercises for a specific stage
 * - `GET /programmed_exercise/` - Retrieve all programmed exercises
 * - `PATCH /programmed_exercise/{id}` - Update an existing programmed exercise
 * - `DELETE /programmed_exercise/{id}` - Delete a programmed exercise
 *
 * ## Error Handling
 *
 * - **404 Not Found**: When a programmed exercise with the specified ID doesn't exist
 * - **422 Unprocessable Entity**: When validation fails
 * - **500 Internal Server Error**: When database operations fail
 *
 * @property programmedExerciseDAL Data access layer for programmed exercise operations
 *
 * @author Congen Development Team
 * @since 1.0.0
 */
@RestController
@RequestMapping("/programmed_exercise")
class ProgrammedExerciseController(
    private val programmedExerciseService: ProgrammedExerciseService,
    private val workoutStageService: WorkoutStageService,
    private val keycloakUtil: KeycloakUtil,
    private val gdprComplianceService: GdprComplianceService
) {
    companion object {
        /** Logger instance for this class. */
        private val logger = LoggerFactory.getLogger(ProgrammedExerciseController::class.java)
    }

    /**
     * Creates a new programmed exercise.
     *
     * This endpoint accepts programmed exercise parameters and saves it to the database.
     * The programmed exercise ID is automatically generated by the database. The method
     * returns the created programmed exercise with the generated ID.
     *
     * @param workoutStageId The ID of the workout stage this exercise belongs to
     * @param exerciseName The name of the exercise to be performed
     * @param position The position of this exercise within the stage
     * @param notes Optional notes or instructions for the exercise
     * @return Mono containing the created programmed exercise with generated ID
     */
    @PostMapping("/")
    @PreAuthorize("isAuthenticated()")
    fun save(
        @RequestParam("workout_stage_id") workoutStageId: Long,
        @RequestParam("exercise_name") exerciseName: String,
        @RequestParam position: Int,
        @RequestParam notes: String?,
    ): Mono<ResponseEntity<ProgrammedExercise>> {
        return keycloakUtil.getCurrentUserId().zipWith(keycloakUtil.getCurrentUserRoles()) { userId, roles ->
            Pair(userId, roles)
        }.flatMap { (userId, roles) ->
            val isAdminOrService = roles.contains("admin") || roles.contains("service")
            workoutStageService.isOwner(workoutStageId, userId).flatMap { isOwner ->
                if (isAdminOrService || isOwner) {
                    val consentUserIdMono = if (isAdminOrService) {
                        workoutStageService.getOwner(workoutStageId)
                    } else {
                        Mono.just(userId)
                    }
                    consentUserIdMono.flatMap { ownerId ->
                        gdprComplianceService.withUserConsent(ownerId) {
                            programmedExerciseService.insertProgrammedExercise(workoutStageId, exerciseName, position, notes)
                                .map { savedExercise ->
                                    logger.debug("Saved programmed exercise with id: {}", savedExercise.id)
                                    ResponseEntity.ok(savedExercise)
                                }
                                .doOnError { e ->
                                    logger.error(
                                        "Error saving programmed exercise: {} for stage: {} at position: {}",
                                        exerciseName,
                                        workoutStageId,
                                        position,
                                        e,
                                    )
                                }
                        }
                    }
                } else {
                    Mono.error(AccessDeniedException("Access denied: User is not the owner of this workout stage"))
                }
            }
        }
    }

    /**
     * Retrieves a programmed exercise by its unique identifier.
     *
     * This endpoint fetches a programmed exercise from the database using the provided ID.
     * If no programmed exercise exists with the given ID, a 404 Not Found response is returned.
     *
     * @param id The unique identifier of the programmed exercise to retrieve
     * @return Mono containing the programmed exercise if found, or 404 if not found
     */
    @GetMapping("/{id}")
    @PreAuthorize("isAuthenticated()")
    fun get(
        @PathVariable("id") id: Long,
    ): Mono<ResponseEntity<ProgrammedExercise>> {
        return keycloakUtil.getCurrentUserId().zipWith(keycloakUtil.getCurrentUserRoles())
            .flatMap { tuple ->
                val userId = tuple.t1
                val roles = tuple.t2
                val isAdminOrService = roles.contains("admin") || roles.contains("service")
                
                // First check if the programmed exercise exists
                programmedExerciseService.selectProgrammedExerciseById(id)
                    .flatMap { programmedExercise ->
                        // Programmed exercise exists, now check ownership
                        programmedExerciseService.isOwner(id, userId).flatMap { isOwner ->
                            if (isAdminOrService || isOwner) {
                                val consentUserIdMono = if (isAdminOrService) {
                                    programmedExerciseService.getOwner(id)
                                } else {
                                    Mono.just(userId)
                                }
                                consentUserIdMono.flatMap { ownerId ->
                                    gdprComplianceService.withUserConsent(ownerId) {
                                        Mono.just(ResponseEntity.ok(programmedExercise))
                                    }
                                }
                            } else {
                                Mono.error(AccessDeniedException("Access denied: User is not the owner of this programmed exercise"))
                            }
                        }
                    }
                    .doOnError { e ->
                        logger.error("Error getting programmed exercise: {}", id, e)
                    }
            }
    }

    /**
     * Retrieves all programmed exercises for a specific workout stage.
     *
     * This endpoint fetches all programmed exercises that belong to a specific
     * workout stage, ordered by their position within the stage.
     *
     * @param workoutStageId The unique identifier of the workout stage
     * @return ResponseEntity containing a list of programmed exercises for the stage
     */
    @GetMapping("/stage/{workout_stage_id}")
    @PreAuthorize("isAuthenticated()")
    fun getByStage(
        @PathVariable("workout_stage_id") workoutStageId: Long,
    ): Mono<ResponseEntity<List<ProgrammedExercise>>> {
        return keycloakUtil.getCurrentUserId().zipWith(keycloakUtil.getCurrentUserRoles()) { userId, roles ->
            Pair(userId, roles)
        }.flatMap { (userId, roles) ->
            val isAdminOrService = roles.contains("admin") || roles.contains("service")
            val programmedExerciseMono =
                if (isAdminOrService) {
                    programmedExerciseService.selectProgrammedExercisesByWorkoutStageId(workoutStageId)
                } else {
                    workoutStageService.isOwner(workoutStageId, userId).flatMap { isOwner ->
                        if (isOwner) {
                            programmedExerciseService.selectProgrammedExercisesByWorkoutStageId(workoutStageId)
                        } else {
                            Mono.error(AccessDeniedException("Access denied: User is not the owner of this workout stage"))
                        }
                    }
                }
            programmedExerciseMono.map { programmedExercises ->
                logger.debug("Found {} programmed exercises for stage: {}", programmedExercises.size, workoutStageId)
                ResponseEntity.ok(programmedExercises)
            }
                .doOnError { e ->
                    logger.error("Error getting programmed exercises for stage: {}", workoutStageId, e)
                }
        }
    }

    /**
     * Retrieves all programmed exercises from the database.
     *
     * This endpoint fetches all programmed exercise records and returns them as a list.
     * If no programmed exercises exist, an empty list is returned.
     *
     * @return ResponseEntity containing a list of all programmed exercises
     */
    @GetMapping("/")
    @PreAuthorize("isAuthenticated()")
    fun getAll(): Mono<ResponseEntity<List<ProgrammedExercise>>> {
        return keycloakUtil.getCurrentUserId().zipWith(keycloakUtil.getCurrentUserRoles()).flatMap { tuple ->
            val userId = tuple.t1
            val roles = tuple.t2
            val isAdminOrService = roles.contains("admin") || roles.contains("service")
            if (isAdminOrService) {
                programmedExerciseService.selectProgrammedExercises()
                    .flatMap { programmedExercises ->
                        Flux.fromIterable(programmedExercises)
                            .flatMap { programmedExercise ->
                                programmedExerciseService.getOwner(programmedExercise.id)
                                    .flatMap { ownerId ->
                                        gdprComplianceService.hasUserConsent(ownerId)
                                            .filter { hasConsent -> hasConsent }
                                            .map { programmedExercise }
                                    }
                            }
                            .collectList()
                    }
                    .map { programmedExercises -> ResponseEntity.ok(programmedExercises) }
            } else {
                gdprComplianceService.withUserConsent(userId) {
                    programmedExerciseService.selectProgrammedExercisesByUserId(userId)
                        .map { programmedExercises -> ResponseEntity.ok(programmedExercises) }
                }
            }
        }
    }

    /**
     * Updates an existing programmed exercise.
     *
     * This endpoint updates a programmed exercise with the specified ID using the provided
     * parameters. The ID from the path parameter is used to ensure the correct
     * programmed exercise is updated. If no programmed exercise exists with the given ID,
     * a 404 Not Found response is returned.
     *
     * @param id The unique identifier of the programmed exercise to update
     * @param workoutStageId The updated workout stage ID
     * @param exerciseName The updated exercise name
     * @param position The updated position of this exercise within the stage
     * @param notes Optional notes for the exercise
     * @return Mono containing the updated programmed exercise, or 404 if not found
     */
    @PatchMapping("/{id}")
    @PreAuthorize("isAuthenticated()")
    fun update(
        @PathVariable("id") id: Long,
        @RequestParam("workout_stage_id") workoutStageId: Long,
        @RequestParam("exercise_name") exerciseName: String,
        @RequestParam("position") position: Int,
        @RequestParam("notes", required = false) notes: String?,
    ): Mono<ResponseEntity<ProgrammedExercise>> {
        return keycloakUtil.getCurrentUserId().zipWith(keycloakUtil.getCurrentUserRoles())
            .flatMap { tuple ->
                val userId = tuple.t1
                val roles = tuple.t2
                val isAdminOrService = roles.contains("admin") || roles.contains("service")
                
                // First check if the programmed exercise exists
                programmedExerciseService.selectProgrammedExerciseById(id)
                    .flatMap {
                        // Programmed exercise exists, now check ownership
                        workoutStageService.isOwner(workoutStageId, userId)
                            .zipWith(programmedExerciseService.isOwner(id, userId)) { isStageOwner, isExerciseOwner ->
                                isStageOwner && isExerciseOwner
                            }.flatMap { hasAccess ->
                                if (isAdminOrService || hasAccess) {
                                    val consentUserIdMono = if (isAdminOrService) {
                                        programmedExerciseService.getOwner(id)
                                    } else {
                                        Mono.just(userId)
                                    }
                                    consentUserIdMono.flatMap { ownerId ->
                                        gdprComplianceService.withUserConsent(ownerId) {
                                            programmedExerciseService.updateProgrammedExercise(id, workoutStageId, exerciseName, position, notes)
                                                .map {
                                                    logger.debug("Updated programmed exercise: {}", id)
                                                    ResponseEntity.ok(it)
                                                }
                                                .doOnError { e ->
                                                    logger.error("Error updating programmed exercise: {}", id, e)
                                                }
                                        }
                                    }
                                } else {
                                    Mono.error(
                                        AccessDeniedException("Access denied: User is not the owner of this workout stage and programmed exercise")
                                    )
                                }
                            }
                    }
                    .doOnError { e ->
                        logger.error("Error updating programmed exercise: {}", id, e)
                    }
            }
    }

    /**
     * Deletes a programmed exercise by its unique identifier.
     *
     * This endpoint removes a programmed exercise from the database using the provided ID.
     * If no programmed exercise exists with the given ID, a 404 Not Found response is returned.
     * The method returns the deleted programmed exercise data for confirmation.
     *
     * @param id The unique identifier of the programmed exercise to delete
     * @return Mono containing the deleted programmed exercise, or 404 if not found
     */
    @DeleteMapping("/{id}")
    @PreAuthorize("isAuthenticated()")
    fun delete(
        @PathVariable("id") id: Long,
    ): Mono<ResponseEntity<ProgrammedExercise>> {
        return keycloakUtil.getCurrentUserId().zipWith(keycloakUtil.getCurrentUserRoles())
            .flatMap { tuple ->
                val userId = tuple.t1
                val roles = tuple.t2
                val isAdminOrService = roles.contains("admin") || roles.contains("service")
                
                // First check if the programmed exercise exists
                programmedExerciseService.selectProgrammedExerciseById(id)
                    .flatMap {
                        // Programmed exercise exists, now check ownership
                        programmedExerciseService.isOwner(id, userId).flatMap { isOwner ->
                            if (isAdminOrService || isOwner) {
                                val consentUserIdMono = if (isAdminOrService) {
                                    programmedExerciseService.getOwner(id)
                                } else {
                                    Mono.just(userId)
                                }
                                consentUserIdMono.flatMap { ownerId ->
                                    gdprComplianceService.withUserConsent(ownerId) {
                                        programmedExerciseService.deleteProgrammedExercise(id)
                                            .map {
                                                logger.debug("Deleted programmed exercise: {}", id)
                                                ResponseEntity.ok(it)
                                            }
                                            .doOnError { e ->
                                                logger.error("Error deleting programmed exercise: {}", id, e)
                                            }
                                    }
                                }
                            } else {
                                Mono.error(AccessDeniedException("Access denied: User is not the owner of this programmed exercise"))
                            }
                        }
                    }
                    .doOnError { e ->
                        logger.error("Error deleting programmed exercise: {}", id, e)
                    }
            }
    }
}
