package com.congen.controllers

import com.congen.model.SetScheme
import com.congen.service.ProgrammedExerciseService
import com.congen.service.SetSchemeService
import com.congen.util.KeycloakUtil
import org.slf4j.LoggerFactory
import org.springframework.http.ResponseEntity
import org.springframework.security.access.prepost.PreAuthorize
import org.springframework.web.bind.annotation.DeleteMapping
import org.springframework.web.bind.annotation.GetMapping
import org.springframework.web.bind.annotation.PatchMapping
import org.springframework.web.bind.annotation.PathVariable
import org.springframework.web.bind.annotation.PostMapping
import org.springframework.web.bind.annotation.RequestMapping
import org.springframework.web.bind.annotation.RequestParam
import org.springframework.web.bind.annotation.RestController
import reactor.core.publisher.Mono

/**
 * REST controller for SetScheme entity operations.
 *
 * This controller provides CRUD operations for set schemes in the Congen API.
 * Set schemes define the specific parameters for individual sets within a
 * programmed exercise, including weight, reps, tempo, and rest periods.
 *
 * ## SetScheme Entity
 *
 * A set scheme represents the configuration for a specific set within an exercise:
 * - Unique identifier and set number within the exercise
 * - Reference to the parent programmed exercise
 * - Target and performed weight, reps, and tempo
 * - Rest period and completion status
 *
 * ## Endpoints
 *
 * - `POST /set_scheme/` - Create a new set scheme
 * - `GET /set_scheme/{id}` - Retrieve a set scheme by ID
 * - `GET /set_scheme/` - Retrieve all set schemes
 * - `GET /set_scheme/exercise/{programmedExerciseId}` - Get schemes for a specific exercise
 * - `PATCH /set_scheme/{id}` - Update an existing set scheme
 * - `DELETE /set_scheme/{id}` - Delete a set scheme
 *
 * ## Error Handling
 *
 * - **404 Not Found**: When a set scheme with the specified ID doesn't exist
 * - **422 Unprocessable Entity**: When validation fails
 * - **500 Internal Server Error**: When database operations fail
 *
 * @property setSchemeService Service layer for set scheme operations
 *
 * @author Congen Development Team
 * @since 1.0.0
 */
@RestController
@RequestMapping("/set_scheme")
class SetSchemeController(
    private val setSchemeService: SetSchemeService,
    private val keycloakUtil: KeycloakUtil,
    private val programmedExerciseService: ProgrammedExerciseService,
) {
    companion object {
        /** Logger instance for this class. */
        private val logger = LoggerFactory.getLogger(SetSchemeController::class.java)
    }

    /**
     * Creates a new set scheme.
     *
     * This endpoint accepts set scheme parameters and saves it to the database.
     * The set scheme ID is automatically generated by the database. The method
     * returns the created set scheme with the generated ID.
     *
     * @param programmedExerciseId The ID of the programmed exercise this set belongs to
     * @param setNumber The set number within the exercise
     * @param isAmrap As Many Reps As Possible flag
     * @param isEmom Every Minute On the Minute flag
     * @param useTempo Whether to use tempo timing
     * @param eccentricTempo Eccentric phase tempo (0-9 seconds)
     * @param isometricTempo Isometric phase tempo (0-9 seconds)
     * @param concentricTempo Concentric phase tempo (0-9 seconds)
     * @param targetWeight Target weight for the set in kg
     * @param performedWeight Actual weight used in kg
     * @param targetRepCount Target number of repetitions
     * @param performedRepCount Actual number of repetitions completed
     * @param restSeconds Rest period after the set in seconds
     * @param unit Optional unit for weight values (KG or LBS). Defaults to KG
     * @return Mono containing the created set scheme with generated ID
     */
    @PostMapping("/")
    @PreAuthorize("hasRole('admin') or hasRole('service') or @programmedExerciseService.isOwner(#programmedExerciseId, principal.subject)")
    fun save(
        @RequestParam("programmed_exercise_id") programmedExerciseId: Long,
        @RequestParam("set_number") setNumber: Int,
        @RequestParam("is_amrap") isAmrap: Boolean,
        @RequestParam("is_emom") isEmom: Boolean,
        @RequestParam("use_tempo") useTempo: Boolean,
        @RequestParam("eccentric_tempo") eccentricTempo: String?,
        @RequestParam("isometric_tempo") isometricTempo: String?,
        @RequestParam("concentric_tempo") concentricTempo: String?,
        @RequestParam("target_weight") targetWeight: String?,
        @RequestParam("performed_weight") performedWeight: String?,
        @RequestParam("target_rep_count") targetRepCount: Int?,
        @RequestParam("performed_rep_count") performedRepCount: Int?,
        @RequestParam("rest_seconds") restSeconds: Int?,
        @RequestParam(required = false, defaultValue = "KG") unit: String?,
    ): Mono<ResponseEntity<SetScheme>> {
        return setSchemeService.createSetScheme(
            programmedExerciseId,
            setNumber,
            isAmrap,
            isEmom,
            useTempo,
            eccentricTempo,
            isometricTempo,
            concentricTempo,
            targetWeight,
            performedWeight,
            targetRepCount,
            performedRepCount,
            restSeconds,
            unit
        )
            .map { setScheme -> ResponseEntity.ok(setScheme) }
    }

    /**
     * Retrieves a set scheme by its unique identifier.
     *
     * This endpoint fetches a set scheme from the database using the provided ID.
     * If no set scheme exists with the given ID, an error response is returned.
     *
     * @param id The unique identifier of the set scheme to retrieve
     * @return Mono containing the set scheme if found
     */
    @GetMapping("/{id}")
    @PreAuthorize("hasRole('admin') or hasRole('service') or @setSchemeService.isOwner(#id, principal.subject)")
    fun get(
        @PathVariable("id") id: Long,
    ): Mono<ResponseEntity<SetScheme>> {
        return setSchemeService.selectSetSchemeById(id)
            .map { setScheme -> ResponseEntity.ok(setScheme) }
    }

    /**
     * Retrieves all set schemes from the database.
     *
     * This endpoint fetches all set scheme records and returns them as a list.
     * If no set schemes exist, an empty list is returned.
     *
     * @return ResponseEntity containing a list of all set schemes
     */
    @GetMapping("/")
    @PreAuthorize("isAuthenticated()")
    fun getAll(): Mono<ResponseEntity<List<SetScheme>>> {
        return keycloakUtil.getCurrentUserId().zipWith(keycloakUtil.getCurrentUserRoles()).flatMap { tuple ->
            val userId = tuple.t1
            val roles = tuple.t2
            val isAdminOrService = roles.contains("admin") || roles.contains("service")
            val setSchemeMono =
                if (isAdminOrService) {
                    setSchemeService.selectSetSchemes()
                } else {
                    setSchemeService.selectSetSchemesByUserId(userId.toInt())
                }
            setSchemeMono.map { ResponseEntity.ok(it) }
        }
    }

    /**
     * Retrieves all set schemes for a specific programmed exercise.
     *
     * This endpoint fetches all set schemes that belong to a specific
     * programmed exercise, ordered by their set number within the exercise.
     *
     * @param programmedExerciseId The unique identifier of the programmed exercise
     * @return ResponseEntity containing a list of set schemes for the exercise
     */
    @GetMapping("/exercise/{programmed_exercise_id}")
    @PreAuthorize("hasRole('admin') or hasRole('service') or @programmedExerciseService.isOwner(#programmedExerciseId, principal.subject)")
    fun getByProgrammedExerciseId(
        @PathVariable("programmed_exercise_id") programmedExerciseId: Long,
    ): Mono<ResponseEntity<List<SetScheme>>> {
        return setSchemeService.selectSetSchemesByProgrammedExerciseId(programmedExerciseId)
            .map { setSchemes -> ResponseEntity.ok(setSchemes) }
    }

    /**
     * Updates an existing set scheme.
     *
     * This endpoint updates a set scheme using the provided parameters.
     * The set scheme ID from the path parameter is used to identify which scheme
     * to update.
     *
     * @param id The unique identifier of the set scheme to update
     * @param programmedExerciseId The updated programmed exercise ID
     * @param setNumber The updated set number within the exercise
     * @param isAmrap The updated As Many Reps As Possible flag
     * @param isEmom The updated Every Minute On the Minute flag
     * @param useTempo The updated flag indicating whether to use tempo timing
     * @param eccentricTempo The updated eccentric phase tempo (0-9 seconds)
     * @param isometricTempo The updated isometric phase tempo (0-9 seconds)
     * @param concentricTempo The updated concentric phase tempo (0-9 seconds)
     * @param targetWeight The updated target weight for the set in kg
     * @param performedWeight The updated actual weight used in kg
     * @param targetRepCount The updated target number of repetitions
     * @param performedRepCount The updated actual number of repetitions completed
     * @param restSeconds The updated rest period after the set in seconds
     * @param unit Optional unit for weight values (KG or LBS). Defaults to KG
     * @return ResponseEntity containing the updated set scheme
     */
    @PatchMapping("/{id}")
    @PreAuthorize(
        "hasRole('admin') or hasRole('service') or (@setSchemeService.isOwner(#id, principal.subject) and @programmedExerciseService.isOwner(#programmedExerciseId, principal.subject))"
    )
    fun update(
        @PathVariable("id") id: Long,
        @RequestParam("programmed_exercise_id") programmedExerciseId: Long,
        @RequestParam("set_number") setNumber: Int,
        @RequestParam("is_amrap") isAmrap: Boolean,
        @RequestParam("is_emom") isEmom: Boolean,
        @RequestParam("use_tempo") useTempo: Boolean,
        @RequestParam("eccentric_tempo") eccentricTempo: String?,
        @RequestParam("isometric_tempo") isometricTempo: String?,
        @RequestParam("concentric_tempo") concentricTempo: String?,
        @RequestParam("target_weight") targetWeight: String?,
        @RequestParam("performed_weight") performedWeight: String?,
        @RequestParam("target_rep_count") targetRepCount: Int?,
        @RequestParam("performed_rep_count") performedRepCount: Int?,
        @RequestParam("rest_seconds") restSeconds: Int?,
        @RequestParam(required = false, defaultValue = "KG") unit: String?,
    ): Mono<ResponseEntity<SetScheme>> {
        return setSchemeService.updateSetSchemeWithUnit(
            id,
            programmedExerciseId,
            setNumber,
            isAmrap,
            isEmom,
            useTempo,
            eccentricTempo,
            isometricTempo,
            concentricTempo,
            targetWeight,
            performedWeight,
            targetRepCount,
            performedRepCount,
            restSeconds,
            unit
        )
            .map { setScheme -> ResponseEntity.ok(setScheme) }
    }

    /**
     * Deletes a set scheme by its unique identifier.
     *
     * This endpoint removes a set scheme from the database using the provided ID.
     * The method returns the deleted set scheme data for confirmation.
     *
     * @param id The unique identifier of the set scheme to delete
     * @return ResponseEntity containing the deleted set scheme
     */
    @DeleteMapping("/{id}")
    @PreAuthorize("hasRole('admin') or hasRole('service') or @setSchemeService.isOwner(#id, principal.subject)")
    fun delete(
        @PathVariable("id") id: Long,
    ): Mono<ResponseEntity<SetScheme>> {
        return setSchemeService.deleteSetScheme(id)
            .map { setScheme -> ResponseEntity.ok(setScheme) }
    }
}
