package com.congen.controllers

import com.congen.model.WorkoutStage
import com.congen.service.ProgramService
import com.congen.service.ProgrammedWorkoutService
import com.congen.service.WorkoutStageService
import com.congen.util.KeycloakUtil
import io.swagger.v3.oas.annotations.Parameter
import org.slf4j.LoggerFactory
import org.springframework.http.ResponseEntity
import org.springframework.security.access.AccessDeniedException
import org.springframework.security.access.prepost.PreAuthorize
import org.springframework.web.bind.annotation.DeleteMapping
import org.springframework.web.bind.annotation.GetMapping
import org.springframework.web.bind.annotation.PatchMapping
import org.springframework.web.bind.annotation.PathVariable
import org.springframework.web.bind.annotation.PostMapping
import org.springframework.web.bind.annotation.RequestMapping
import org.springframework.web.bind.annotation.RequestParam
import org.springframework.web.bind.annotation.RestController
import reactor.core.publisher.Mono

/**
 * REST controller for WorkoutStage entity operations.
 *
 * This controller provides CRUD operations for workout stages in the Congen API.
 * Workout stages represent individual components of a programmed workout, such as
 * warm-up, main exercises, and cool-down periods.
 *
 * ## WorkoutStage Entity
 *
 * A workout stage represents a component of a programmed workout with:
 * - Unique identifier and position within the workout
 * - Reference to the parent programmed workout
 * - Stage type (warm-up, main, cool-down, etc.)
 * - Associated programmed exercises
 *
 * ## Endpoints
 *
 * - `POST /workout_stage/` - Create a new workout stage
 * - `GET /workout_stage/{id}` - Retrieve a workout stage by ID
 * - `GET /workout_stage/` - Retrieve all workout stages
 * - `GET /workout_stage/workout/{programmedWorkoutId}` - Get stages for a specific workout
 * - `PATCH /workout_stage/` - Update an existing workout stage
 * - `DELETE /workout_stage/{id}` - Delete a workout stage
 *
 * ## Error Handling
 *
 * - **404 Not Found**: When a workout stage with the specified ID doesn't exist
 * - **422 Unprocessable Entity**: When validation fails
 * - **500 Internal Server Error**: When database operations fail
 *
 * @property workoutStageDAL Data access layer for workout stage operations
 *
 * @author Congen Development Team
 * @since 1.0.0
 */
@RestController
@RequestMapping("/workout_stage")
class WorkoutStageController(
    private val workoutStageService: WorkoutStageService,
    private val programService: ProgramService,
    private val programmedWorkoutService: ProgrammedWorkoutService,
    private val keycloakUtil: KeycloakUtil
) {
    companion object {
        /** Logger instance for this class. */
        private val logger = LoggerFactory.getLogger(WorkoutStageController::class.java)
    }

    /**
     * Creates a new workout stage.
     *
     * This endpoint accepts individual parameters and saves a new workout stage to the database.
     * The workout stage ID is automatically generated by the database. The method
     * returns the created workout stage with the generated ID.
     *
     * @param programmedWorkoutId The ID of the programmed workout this stage belongs to
     * @param stageTypeId The ID of the stage type (warm-up, main, cool-down, etc.)
     * @param position The position of this stage within the workout
     * @param name The name of the workout stage
     * @return Mono containing the created workout stage with generated ID
     */
    @PostMapping("/")
    @PreAuthorize("isAuthenticated()")
    fun save(
        @Parameter(description = "Programmed workout ID", required = true)
        @RequestParam("programmed_workout_id") programmedWorkoutId: Long,
        @Parameter(description = "Stage type ID", required = true)
        @RequestParam("stage_type_id") stageTypeId: Int,
        @Parameter(description = "Position within the workout", required = true)
        @RequestParam position: Int,
        @Parameter(description = "Name of the workout stage", required = true)
        @RequestParam name: String,
    ): Mono<ResponseEntity<WorkoutStage>> {
        return keycloakUtil.getCurrentUserId().zipWith(keycloakUtil.getCurrentUserRoles()) { userId, roles ->
            Pair(userId, roles)
        }.flatMap { (userId, roles) ->
            val isAdminOrService = roles.contains("admin") || roles.contains("service")
            val workoutStageMono =
                if (isAdminOrService) {
                    workoutStageService.insertWorkoutStage(programmedWorkoutId, stageTypeId, position, name)
                } else {
                    // First check if the programmed workout exists, then check ownership
                    programmedWorkoutService.selectProgrammedWorkoutById(programmedWorkoutId)
                        .flatMap { programmedWorkout ->
                            programService.isOwner(programmedWorkout.programId, userId).flatMap { isOwner ->
                                if (isOwner) {
                                    workoutStageService.insertWorkoutStage(programmedWorkoutId, stageTypeId, position, name)
                                } else {
                                    Mono.error(AccessDeniedException("Access denied: User is not the owner of this programmed workout"))
                                }
                            }
                        }
                        .doOnError { e ->
                            logger.error("Error checking ownership for workout stage creation: {}", programmedWorkoutId, e)
                        }
                }

            workoutStageMono.map {
                logger.debug("Saved workout stage with id: {}", it.id)
                ResponseEntity.ok(it)
            }
                .doOnError { e ->
                    logger.error(
                        "Error saving workout stage for workout: {}, position: {}, name: {}",
                        programmedWorkoutId,
                        position,
                        name,
                        e,
                    )
                }
        }
    }

    /**
     * Retrieves a workout stage by its unique identifier.
     *
     * This endpoint fetches a workout stage from the database using the provided ID.
     * If no workout stage exists with the given ID, an error response is returned.
     *
     * @param id The unique identifier of the workout stage to retrieve
     * @return Mono containing the workout stage if found
     */
    @GetMapping("/{id}")
    @PreAuthorize("isAuthenticated()")
    fun get(
        @PathVariable("id") id: Long,
    ): Mono<ResponseEntity<WorkoutStage>> {
        return keycloakUtil.getCurrentUserId().zipWith(keycloakUtil.getCurrentUserRoles()) { userId, roles ->
            Pair(userId, roles)
        }.flatMap { (userId, roles) ->
            val isAdminOrService = roles.contains("admin") || roles.contains("service")
            val workoutStageMono =
                if (isAdminOrService) {
                    workoutStageService.selectWorkoutStageById(id)
                } else {
                    // First check if the workout stage exists, then check ownership
                    workoutStageService.selectWorkoutStageById(id)
                        .flatMap { workoutStage ->
                            workoutStageService.isOwner(workoutStage.id, userId).flatMap { isOwner ->
                                if (isOwner) {
                                    Mono.just(workoutStage)
                                } else {
                                    Mono.error(AccessDeniedException("Access denied: User is not the owner of this workout stage"))
                                }
                            }
                        }
                }

            workoutStageMono.map {
                logger.debug("Found workout stage: {}", id)
                ResponseEntity.ok(it)
            }
                .doOnError { e ->
                    logger.error("Error getting workout stage: {}", id, e)
                }
        }
    }

    /**
     * Retrieves all workout stages from the database.
     *
     * This endpoint fetches all workout stage records and returns them as a list.
     * If no workout stages exist, an empty list is returned.
     *
     * @return ResponseEntity containing a list of all workout stages
     */
    @GetMapping("/")
    @PreAuthorize("isAuthenticated()")
    fun getAll(): Mono<ResponseEntity<List<WorkoutStage>>> {
        return keycloakUtil.getCurrentUserId().zipWith(keycloakUtil.getCurrentUserRoles()).flatMap { tuple ->
            val userId = tuple.t1
            val roles = tuple.t2
            val isAdminOrService = roles.contains("admin") || roles.contains("service")
            val workoutStageMono =
                if (isAdminOrService) {
                    workoutStageService.selectWorkoutStages()
                } else {
                    workoutStageService.selectWorkoutStagesByUserId(userId)
                }
            workoutStageMono.map { ResponseEntity.ok(it) }
        }
    }

    /**
     * Retrieves all workout stages for a specific programmed workout.
     *
     * This endpoint fetches all workout stages that belong to a specific
     * programmed workout, ordered by their position within the workout.
     *
     * @param programmedWorkoutId The unique identifier of the programmed workout
     * @return ResponseEntity containing a list of workout stages for the workout
     */
    @GetMapping("/workout/{programmed_workout_id}")
    @PreAuthorize("isAuthenticated()")
    fun getByProgrammedWorkoutId(
        @PathVariable("programmed_workout_id") programmedWorkoutId: Long,
    ): Mono<ResponseEntity<List<WorkoutStage>>> {
        return keycloakUtil.getCurrentUserId().zipWith(keycloakUtil.getCurrentUserRoles()) { userId, roles ->
            Pair(userId, roles)
        }.flatMap { (userId, roles) ->
            val isAdminOrService = roles.contains("admin") || roles.contains("service")
            val workoutStageMono =
                if (isAdminOrService) {
                    workoutStageService.selectWorkoutStagesByProgrammedWorkoutId(programmedWorkoutId)
                } else {
                    // First check if the programmed workout exists, then check ownership
                    programmedWorkoutService.selectProgrammedWorkoutById(programmedWorkoutId)
                        .flatMap { programmedWorkout ->
                            programService.isOwner(programmedWorkout.programId, userId).flatMap { isOwner ->
                                if (isOwner) {
                                    logger.debug("Getting workout stages for programmed workout: {}", programmedWorkoutId)
                                    workoutStageService.selectWorkoutStagesByProgrammedWorkoutId(programmedWorkoutId)
                                } else {
                                    Mono.error(AccessDeniedException("Access denied: User is not the owner of this programmed workout"))
                                }
                            }
                        }
                        .doOnError { e ->
                            logger.error("Error checking ownership for workout stages: {}", programmedWorkoutId, e)
                        }
                }

            workoutStageMono.map {
                logger.debug("Found {} workout stages for programmed workout: {}", it.size, programmedWorkoutId)
                ResponseEntity.ok(it)
            }
                .doOnError { e ->
                    logger.error("Error getting workout stages for programmed workout: {}", programmedWorkoutId, e)
                }
        }
    }

    /**
     * Updates an existing workout stage.
     *
     * This endpoint updates a workout stage using the provided individual parameters.
     * The workout stage ID is used to identify which stage to update.
     *
     * @param id The unique identifier of the workout stage to update
     * @param programmedWorkoutId The ID of the programmed workout this stage belongs to
     * @param stageTypeId The ID of the stage type (warm-up, main, cool-down, etc.)
     * @param position The position of this stage within the workout
     * @param name The name of the workout stage
     * @return ResponseEntity containing the updated workout stage
     */
    @PatchMapping("/")
    @PreAuthorize("isAuthenticated()")
    fun update(
        @Parameter(description = "Workout stage ID", required = true)
        @RequestParam id: Long,
        @Parameter(description = "Programmed workout ID", required = true)
        @RequestParam("programmed_workout_id") programmedWorkoutId: Long,
        @Parameter(description = "Stage type ID", required = true)
        @RequestParam("stage_type_id") stageTypeId: Int,
        @Parameter(description = "Position within the workout", required = true)
        @RequestParam position: Int,
        @Parameter(description = "Name of the workout stage", required = true)
        @RequestParam name: String,
    ): Mono<ResponseEntity<WorkoutStage>> {
        return keycloakUtil.getCurrentUserId().zipWith(keycloakUtil.getCurrentUserRoles()) { userId, roles ->
            Pair(userId, roles)
        }.flatMap { (userId, roles) ->
            val isAdminOrService = roles.contains("admin") || roles.contains("service")
            val workoutStageMono =
                if (isAdminOrService) {
                    workoutStageService.updateWorkoutStage(id, programmedWorkoutId, stageTypeId, position, name)
                } else {
                    workoutStageService.isOwner(id, userId).flatMap { isWorkoutStageOwner ->
                        if (isWorkoutStageOwner) {
                            programmedWorkoutService.isOwner(programmedWorkoutId, userId).flatMap { isProgrammedWorkoutOwner ->
                                if (isProgrammedWorkoutOwner) {
                                    workoutStageService.updateWorkoutStage(id, programmedWorkoutId, stageTypeId, position, name)
                                } else {
                                    Mono.error(AccessDeniedException("Access denied: User is not the owner of this programmed workout"))
                                }
                            }
                        } else {
                            Mono.error(AccessDeniedException("Access denied: User is not the owner of this workout stage"))
                        }
                    }
                }

            workoutStageMono.map {
                logger.debug("Updated workout stage: {}", id)
                ResponseEntity.ok(it)
            }
                .doOnError { e ->
                    logger.error("Error updating workout stage: {}", id, e)
                }
        }
    }

    /**
     * Deletes a workout stage by its unique identifier.
     *
     * This endpoint removes a workout stage from the database using the provided ID.
     * The method returns the deleted workout stage data for confirmation.
     *
     * @param id The unique identifier of the workout stage to delete
     * @return ResponseEntity containing the deleted workout stage
     */
    @DeleteMapping("/{id}")
    @PreAuthorize("isAuthenticated()")
    fun delete(
        @PathVariable("id") id: Long,
    ): Mono<ResponseEntity<WorkoutStage>> {
        return keycloakUtil.getCurrentUserId().zipWith(keycloakUtil.getCurrentUserRoles()) { userId, roles ->
            Pair(userId, roles)
        }.flatMap { (userId, roles) ->
            val isAdminOrService = roles.contains("admin") || roles.contains("service")
            val workoutStageMono =
                if (isAdminOrService) {
                    workoutStageService.deleteWorkoutStage(id)
                } else {
                    // First check if the workout stage exists, then check ownership
                    workoutStageService.isOwner(id, userId).flatMap { isOwner ->
                        if (isOwner) {
                            workoutStageService.deleteWorkoutStage(id)
                        } else {
                            Mono.error(AccessDeniedException("Access denied: User is not the owner of this workout stage"))
                        }
                    }
                }

            workoutStageMono.map {
                logger.debug("Deleted workout stage: {}", id)
                ResponseEntity.ok(it)
            }
                .doOnError { e ->
                    logger.error("Error deleting workout stage: {}", id, e)
                }
        }
    }
}
