spring.application.name=congen

server.subservice.metrics-namespace=congen

server.compression.enabled=true
server.compression.min-response-size=5120
server.compression.mime-types=application/json,application/x-protobuf

server.shutdown=graceful
spring.lifecycle.timeout-per-shutdown-phase=10s

server.port=8080

springdoc.api-docs.enabled=false
springdoc.swagger-ui.enabled=false

spring.r2dbc.url=r2dbc:postgresql://localhost:5432/postgres
spring.r2dbc.username=postgres
spring.r2dbc.password=postgres
spring.data.r2dbc.repositories.enabled=true
