#Generated version information
#Fri Jul 04 11:07:26 EDT 2025
app.releaseId=main-73ce01579f-1751641646211
app.gitHash=73ce01579f
app.buildTime=2025-07-04T11\:07\:26Z
app.gitDirty=true
app.gitBranch=main
app.version=0.0.1-SNAPSHOT
