#Generated version information
#Sun Jul 06 13:07:20 EDT 2025
app.releaseId=main-4d45f589a6-1751821640741
app.gitHash=4d45f589a6
app.buildTime=2025-07-06T13\:07\:20Z
app.gitDirty=true
app.gitBranch=main
app.version=0.0.1-SNAPSHOT
