apiVersion: v1
kind: Secret
metadata:
  name: congen-secret
  namespace: congen
type: Opaque
data:
  # Base64 encoded values for local development
  PGUSER: cG9zdGdyZXM=      # postgres
  PGPASSWORD: cG9zdGdyZXM=  # postgres
  PGDATABASE: cG9zdGdyZXM=  # postgres
  DB_BASE_URL: amRiYzpwb3N0Z3Jlc3FsOi8v  # jdbc:postgresql://
  PGHOST: cG9zdGdyZXM=  # postgres
  PGPORT: NTQzMg==  # 5432 