apiVersion: v1
kind: Secret
metadata:
  name: congen-secret
  namespace: congen
type: Opaque
data:
  # Base64 encoded values for local development
  PGUSER: cG9zdGdyZXM=      # postgres
  PGPASSWORD: cG9zdGdyZXM=  # postgres
  PGDATABASE: cG9zdGdyZXM=  # postgres 