apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: congen

resources:
  - ../../../base/stage-5
  - postgres-deployment.yaml
  - postgres-service.yaml
  - postgres-configmap.yaml
  - postgres-pvc.yaml
  - memcached-deployment.yaml
  - memcached-service.yaml

patches:
- path: patches/migration-service-labels-patch.yaml
  target:
    kind: Deployment
    name: migration-service
- path: patches/keycloak-migrations-job-patch.yaml
  target:
    kind: Job
    name: keycloak-migrations
