package com.congen.dal

import com.congen.client.PostgresClient
import com.congen.model.ProgrammedExercise
import org.slf4j.LoggerFactory
import org.springframework.stereotype.Component
import reactor.core.publisher.Mono

/**
 * Data Access Layer for ProgrammedExercise entity operations.
 *
 * This class provides database operations for the ProgrammedExercise entity in the Congen application.
 * ProgrammedExercise represents exercises that are assigned to specific workout stages within a workout,
 * including the exercise to be performed and any additional notes or instructions.
 *
 * ## ProgrammedExercise Entity
 *
 * ProgrammedExercise represents:
 * - Exercise assigned to a specific workout stage
 * - Exercise name and workout stage ID
 * - Optional notes or instructions for the exercise
 * - Used for workout structure and exercise sequencing
 *
 * ## Database Operations
 *
 * - **Select by ID**: Retrieve programmed exercise by its unique identifier
 * - **Select by workout stage**: Retrieve all exercises for a specific workout stage
 * - **Select all**: Retrieve all programmed exercise records
 * - **Insert**: Create new programmed exercise records
 * - **Update**: Modify existing programmed exercise properties
 * - **Delete**: Remove programmed exercise records
 *
 * ## Error Handling
 *
 * - **NoResultsFoundException**: When programmed exercise with specified ID doesn't exist
 * - **DatabaseException**: When database operations fail
 *
 * @property postgresClient PostgreSQL client for database operations
 *
 * @author Congen Development Team
 * @since 1.0.0
 */
@Component
class ProgrammedExerciseDAL(
    private val postgresClient: PostgresClient,
) {
    companion object {
        /** Logger instance for this class. */
        private val logger = LoggerFactory.getLogger(ProgrammedExerciseDAL::class.java)
    }

    /**
     * Retrieves a programmed exercise by its unique identifier.
     *
     * This method queries the database to find a programmed exercise with the specified ID.
     * If no programmed exercise exists with the given ID, a NoResultsFoundException is thrown.
     *
     * @param id The unique identifier of the programmed exercise to retrieve
     * @return Mono containing the programmed exercise if found
     * @throws NoResultsFoundException when programmed exercise with the specified ID doesn't exist
     */
    fun selectProgrammedExerciseById(id: Long): Mono<ProgrammedExercise> {
        logger.debug("Selecting programmed exercise by id: {}", id)
        return postgresClient.selectIndividual(
            "SELECT * FROM programmed_exercise WHERE id=$1",
            id,
        )
    }

    /**
     * Retrieves all programmed exercises for a specific workout stage.
     *
     * This method fetches all exercises that are assigned to the specified workout stage.
     * If no exercises exist for the workout stage, an empty list is returned.
     *
     * @param workoutStageId The unique identifier of the workout stage
     * @return Mono containing a list of programmed exercises
     */
    fun selectProgrammedExercisesByWorkoutStageId(workoutStageId: Long): Mono<List<ProgrammedExercise>> {
        logger.debug("Selecting programmed exercises by workout stage id: {}", workoutStageId)
        return postgresClient.select(
            "SELECT * FROM programmed_exercise WHERE workout_stage_id=$1",
            workoutStageId,
        )
    }

    /**
     * Retrieves all programmed exercise records from the database.
     *
     * This method fetches all programmed exercise records and returns them as a list.
     * If no programmed exercises exist, an empty list is returned.
     *
     * @return Mono containing a list of all programmed exercises
     */
    fun selectProgrammedExercises(): Mono<List<ProgrammedExercise>> {
        logger.debug("Selecting all programmed exercises")
        return postgresClient.select("SELECT * FROM programmed_exercise")
    }

    /**
     * Creates a new programmed exercise record in the database.
     *
     * This method inserts a new programmed exercise record with the provided properties.
     * The programmed exercise ID is automatically generated by the database.
     *
     * @param programmedExercise The programmed exercise object to create
     * @return Mono containing the created programmed exercise with generated ID
     * @throws DatabaseException when database operation fails
     */
    fun insertProgrammedExercise(programmedExercise: ProgrammedExercise): Mono<ProgrammedExercise> {
        logger.debug("Inserting programmed exercise: {} for stage: {}", programmedExercise.exerciseName, programmedExercise.workoutStageId)
        return postgresClient.update(
            """
            INSERT INTO programmed_exercise
                (workout_stage_id, exercise_name, notes)
            VALUES
                ($1, $2, $3)
            """.trimIndent(),
            programmedExercise.workoutStageId,
            programmedExercise.exerciseName,
            programmedExercise.notes,
        )
    }

    /**
     * Updates an existing programmed exercise record in the database.
     *
     * This method modifies the properties of the programmed exercise with the specified ID.
     * If no programmed exercise exists with the given ID, a NoResultsFoundException is thrown.
     *
     * @param programmedExercise The programmed exercise object with updated properties
     * @return Mono containing the updated programmed exercise
     * @throws NoResultsFoundException when programmed exercise with the specified ID doesn't exist
     */
    fun updateProgrammedExercise(programmedExercise: ProgrammedExercise): Mono<ProgrammedExercise> {
        logger.debug("Updating programmed exercise: {}", programmedExercise.id)
        return postgresClient.update(
            """
            UPDATE programmed_exercise
            SET workout_stage_id=$2, exercise_name=$3, notes=$4
            WHERE id=$1
            """.trimIndent(),
            programmedExercise.id,
            programmedExercise.workoutStageId,
            programmedExercise.exerciseName,
            programmedExercise.notes,
        )
    }

    /**
     * Deletes a programmed exercise record from the database.
     *
     * This method removes the programmed exercise record with the specified ID.
     * If no programmed exercise exists with the given ID, a NoResultsFoundException is thrown.
     *
     * @param id The unique identifier of the programmed exercise to delete
     * @return Mono containing the deleted programmed exercise
     * @throws NoResultsFoundException when programmed exercise with the specified ID doesn't exist
     */
    fun deleteProgrammedExercise(id: Long): Mono<ProgrammedExercise> {
        logger.debug("Deleting programmed exercise: {}", id)
        return postgresClient.update(
            "DELETE FROM programmed_exercise WHERE id=$1",
            id,
        )
    }

    /**
     * Gets the user ID for a programmed exercise by tracing the relationship chain.
     *
     * This method follows the relationship chain:
     * ProgrammedExercise → WorkoutStage → ProgrammedWorkout → Program → User
     *
     * @param programmedExerciseId The ID of the programmed exercise
     * @return Mono containing the user ID
     * @throws NoResultsFoundException when the relationship chain cannot be traced
     */
    fun getUserIdFromProgrammedExercise(programmedExerciseId: Long): Mono<Int> {
        logger.debug("Getting user ID for programmed exercise: {}", programmedExerciseId)
        return postgresClient.selectIndividual(
            """
            SELECT p.user_id
            FROM programmed_exercise pe
            JOIN workout_stage ws ON pe.workout_stage_id = ws.id
            JOIN programmed_workout pw ON ws.programmed_workout_id = pw.id
            JOIN program p ON pw.program_id = p.id
            WHERE pe.id = $1
            """.trimIndent(),
            programmedExerciseId,
        )
    }
}
