package com.congen.dal

import com.congen.client.PostgresClient
import com.congen.model.Program
import org.slf4j.LoggerFactory
import org.springframework.stereotype.Component
import reactor.core.publisher.Mono

/**
 * Data Access Layer for Program entities.
 *
 * This class provides database operations for Program entities, including CRUD
 * operations. It uses the reactive PostgreSQL client for all database interactions
 * and provides methods for managing workout programs in the system.
 *
 * ## Operations
 *
 * - **Read**: Select program by ID, select all programs
 * - **Create**: Insert new program
 * - **Update**: Update existing program
 * - **Delete**: Delete program by ID
 *
 * ## Program Entity
 *
 * Programs represent structured workout plans that contain:
 * - Unique identifier and name
 * - Description of the program
 * - Associated programmed workouts (via foreign key relationships)
 *
 * ## Database Schema
 *
 * The program table contains:
 * - `id`: Primary key (auto-generated)
 * - `name`: Program name (required)
 * - `description`: Program description (optional)
 *
 * @property postgresClient Client for database operations
 *
 * @author Congen Development Team
 * @since 1.0.0
 */
@Component
class ProgramDAL(
    private val postgresClient: PostgresClient,
) {
    companion object {
        /** Logger instance for this class. */
        private val logger = LoggerFactory.getLogger(ProgramDAL::class.java)
    }

    /**
     * Retrieves a program by its unique identifier.
     *
     * This method queries the database for a program with the specified ID.
     * If no program is found, a [NoResultsFoundException] is thrown.
     *
     * @param id The unique identifier of the program to retrieve
     * @return Mono containing the program if found
     * @throws NoResultsFoundException if no program exists with the given ID
     */
    fun selectProgramById(id: Long): Mono<Program> {
        logger.debug("Selecting program by id: {}", id)
        return postgresClient.selectIndividual(
            "SELECT * FROM program WHERE id=$1",
            id,
        )
    }

    /**
     * Retrieves all programs from the database.
     *
     * This method queries the database for all program records and returns
     * them as a list, ordered by name. If no programs exist, an empty list
     * is returned.
     *
     * @return Mono containing a list of all programs
     */
    fun selectPrograms(): Mono<List<Program>> {
        logger.debug("Selecting all programs")
        return postgresClient.select("SELECT * FROM program ORDER BY name")
    }

    /**
     * Inserts a new program into the database.
     *
     * This method inserts a new program record. The program ID is automatically
     * generated by the database. The method returns the created program with
     * the generated ID.
     *
     * @param program The program object to insert
     * @return Mono containing the inserted program with generated ID
     */
    fun insertProgram(program: Program): Mono<Program> {
        logger.debug("Inserting program: {}", program.name)
        return postgresClient.update(
            """
            INSERT INTO program
                (name, description)
            VALUES
                ($1, $2)
            """.trimIndent(),
            program.name,
            program.description,
        )
    }

    /**
     * Updates an existing program in the database.
     *
     * This method updates the program record with the specified ID using the
     * provided program data. If no program exists with the given ID, a
     * [NoResultsFoundException] is thrown.
     *
     * @param program The program object with updated data
     * @return Mono containing the updated program
     * @throws NoResultsFoundException if no program exists with the given ID
     */
    fun updateProgram(program: Program): Mono<Program> {
        logger.debug("Updating program: {}", program.id)
        return postgresClient.update(
            """
            UPDATE program
            SET name=$2, description=$3
            WHERE id=$1
            """.trimIndent(),
            program.id,
            program.name,
            program.description,
        )
    }

    /**
     * Deletes a program from the database.
     *
     * This method removes the program record with the specified ID from
     * the database. If no program exists with the given ID, a
     * [NoResultsFoundException] is thrown. The method returns the deleted
     * program data for confirmation.
     *
     * @param id The unique identifier of the program to delete
     * @return Mono containing the deleted program
     * @throws NoResultsFoundException if no program exists with the given ID
     */
    fun deleteProgram(id: Long): Mono<Program> {
        logger.debug("Deleting program: {}", id)
        return postgresClient.update(
            "DELETE FROM program WHERE id=$1",
            id,
        )
    }
}
