package com.congen.dal

import com.congen.client.PostgresClient
import com.congen.model.Program
import org.slf4j.LoggerFactory
import org.springframework.stereotype.Component
import reactor.core.publisher.Mono

/**
 * Data Access Layer for Program entities.
 *
 * This class provides database operations for Program entities, including CRUD
 * operations. It uses the reactive PostgreSQL client for all database interactions
 * and provides methods for managing workout programs in the system.
 *
 * ## Operations
 *
 * - **Read**: Select program by ID, select all programs
 * - **Create**: Insert new program
 * - **Update**: Update existing program
 * - **Delete**: Delete program by ID
 *
 * ## Program Entity
 *
 * Programs represent structured workout plans that contain:
 * - Unique identifier and name
 * - Description of the program
 * - Current week number
 * - Associated programmed workouts (via foreign key relationships)
 *
 * ## Database Schema
 *
 * The program table contains:
 * - `id`: Primary key (auto-generated)
 * - `user_id`: User ID (required)
 * - `name`: Program name (required)
 * - `description`: Program description (optional)
 * - `current_week_number`: Current week number (required)
 * - `created_at`: Creation timestamp (auto-generated)
 * - `updated_at`: Last update timestamp (auto-generated)
 *
 * @property postgresClient Client for database operations
 *
 * @author Congen Development Team
 * @since 1.0.0
 */
@Component
class ProgramDAL(
    private val postgresClient: PostgresClient,
) {
    companion object {
        /** Logger instance for this class. */
        private val logger = LoggerFactory.getLogger(ProgramDAL::class.java)
    }

    /**
     * Retrieves a program by its unique identifier.
     *
     * This method queries the database for a program with the specified ID.
     * If no program is found, a [NoResultsFoundException] is thrown.
     *
     * @param id The unique identifier of the program to retrieve
     * @return Mono containing the program if found
     * @throws NoResultsFoundException if no program exists with the given ID
     */
    fun selectProgramById(id: Long): Mono<Program> {
        logger.debug("Selecting program by id: {}", id)
        return postgresClient.selectIndividual(
            "SELECT * FROM program WHERE id=$1",
            id,
        )
    }

    /**
     * Retrieves all programs from the database.
     *
     * This method queries the database for all program records and returns
     * them as a list, ordered by name. If no programs exist, an empty list
     * is returned.
     *
     * @return Mono containing a list of all programs
     */
    fun selectPrograms(): Mono<List<Program>> {
        logger.debug("Selecting all programs")
        return postgresClient.select("SELECT * FROM program ORDER BY name")
    }

    /**
     * Inserts a new program into the database.
     *
     * This method inserts a new program record. The program ID is automatically
     * generated by the database. The method returns the created program with
     * the generated ID.
     *
     * @param userId The user ID for the program
     * @param name The name of the program
     * @param currentWeekNumber The current week number
     * @return Mono containing the inserted program with generated ID
     */
    fun insertProgram(
        userId: Int,
        name: String,
        currentWeekNumber: Int
    ): Mono<Program> {
        logger.debug("Inserting program: {} for user {} with week number {}", name, userId, currentWeekNumber)
        return postgresClient.update(
            """
            INSERT INTO program
                (user_id, name, current_week_number)
            VALUES
                ($1, $2, $3)
            """.trimIndent(),
            userId,
            name,
            currentWeekNumber,
        )
    }

    /**
     * Updates an existing program in the database.
     *
     * This method updates the program record with the specified ID using the
     * provided parameters. If no program exists with the given ID, a
     * [NoResultsFoundException] is thrown.
     *
     * @param id The unique identifier of the program to update
     * @param name The updated name of the program
     * @param currentWeekNumber The updated current week number
     * @return Mono containing the updated program
     * @throws NoResultsFoundException if no program exists with the given ID
     */
    fun updateProgram(
        id: Long,
        name: String,
        currentWeekNumber: Int
    ): Mono<Program> {
        logger.debug("Updating program: {}", id)

        return postgresClient.update(
            """
            UPDATE program
            SET name=$2, current_week_number=$3, updated_at=NOW()
            WHERE id=$1
            """.trimIndent(),
            id,
            name,
            currentWeekNumber,
        )
    }

    /**
     * Deletes a program from the database.
     *
     * This method removes the program record with the specified ID from
     * the database. If no program exists with the given ID, a
     * [NoResultsFoundException] is thrown. The method returns the deleted
     * program data for confirmation.
     *
     * @param id The unique identifier of the program to delete
     * @return Mono containing the deleted program
     * @throws NoResultsFoundException if no program exists with the given ID
     */
    fun deleteProgram(id: Long): Mono<Program> {
        logger.debug("Deleting program: {}", id)
        return postgresClient.update(
            "DELETE FROM program WHERE id=$1",
            id,
        )
    }
}
