package com.congen.dal

import com.congen.client.PostgresClient
import com.congen.model.User
import com.congen.util.ValidationUtil
import org.slf4j.LoggerFactory
import org.springframework.stereotype.Component
import reactor.core.publisher.Mono
import java.math.BigDecimal

/**
 * Data Access Layer for User entities.
 *
 * This class provides database operations for User entities, including CRUD
 * operations and data validation. It uses the reactive PostgreSQL client
 * for all database interactions and includes comprehensive validation
 * of user data before database operations.
 *
 * ## Operations
 *
 * - **Read**: Select user by ID, select all users
 * - **Create**: Insert new user with validation
 * - **Update**: Update existing user with validation
 * - **Delete**: Delete user by ID
 *
 * ## Validation
 *
 * All user data is validated before database operations using [ValidationUtil]:
 * - Age validation (1-150 years)
 * - Height validation (0.01-300 cm)
 * - Weight validation (0.01-1000 kg)
 *
 * @property postgresClient Client for database operations
 *
 * @author Congen Development Team
 * @since 1.0.0
 */
@Component
class UserDAL(
    private val postgresClient: PostgresClient,
) {
    companion object {
        /** Logger instance for this class. */
        private val logger = LoggerFactory.getLogger(UserDAL::class.java)
    }

    /**
     * Retrieves a user by their unique identifier.
     *
     * This method queries the database for a user with the specified ID.
     * If no user is found, a [NoResultsFoundException] is thrown.
     *
     * @param userId The unique identifier of the user to retrieve
     * @return Mono containing the user if found
     * @throws NoResultsFoundException if no user exists with the given ID
     */
    fun selectUserById(userId: Int): Mono<User> {
        logger.debug("Selecting user by id: {}", userId)
        return postgresClient.selectIndividual(
            "SELECT * FROM \"user\" WHERE id=$1",
            userId,
        )
    }

    /**
     * Retrieves all users from the database.
     *
     * This method queries the database for all user records and returns
     * them as a list. If no users exist, an empty list is returned.
     *
     * @return Mono containing a list of all users
     */
    fun selectUsers(): Mono<List<User>> {
        logger.debug("Selecting all users")
        return postgresClient.select("SELECT * FROM \"user\"")
    }

    /**
     * Inserts a new user into the database.
     *
     * This method validates the user data and inserts a new user record.
     * The user ID is automatically generated by the database. All user
     * properties are validated before insertion.
     *
     * @param name The user's full name
     * @param age The user's age in years
     * @param height The user's height in centimeters
     * @param weight The user's weight in kilograms
     * @return Mono containing the inserted user with generated ID
     * @throws ValidationException if user data fails validation
     */
    fun insertUser(name: String, age: Int, height: BigDecimal, weight: BigDecimal): Mono<User> {
        logger.debug("Inserting user: {}", name)

        // Validate all CHECK constraints
        ValidationUtil.validateUserAge(age)
        ValidationUtil.validateUserHeight(height)
        ValidationUtil.validateUserWeight(weight)

        return postgresClient.update(
            """
            INSERT INTO "user"
                (name, age, height, weight)
            VALUES
                ($1, $2, $3, $4)
            """.trimIndent(),
            name,
            age,
            height,
            weight,
        )
    }

    /**
     * Updates an existing user in the database.
     *
     * This method validates the user data and updates the user record
     * with the specified ID. All user properties are validated before
     * the update operation.
     *
     * @param id The unique identifier of the user to update
     * @param name The updated user's full name
     * @param age The updated user's age in years
     * @param height The updated user's height in centimeters
     * @param weight The updated user's weight in kilograms
     * @return Mono containing the updated user
     * @throws ValidationException if user data fails validation
     * @throws NoResultsFoundException if no user exists with the given ID
     */
    fun updateUser(id: Int, name: String, age: Int, height: BigDecimal, weight: BigDecimal): Mono<User> {
        logger.debug("Updating user: {}", id)

        // Validate all CHECK constraints
        ValidationUtil.validateUserAge(age)
        ValidationUtil.validateUserHeight(height)
        ValidationUtil.validateUserWeight(weight)

        return postgresClient.update(
            """
            UPDATE "user"
            SET name=$2, age=$3, height=$4, weight=$5
            WHERE id=$1
            """.trimIndent(),
            id,
            name,
            age,
            height,
            weight,
        )
    }

    /**
     * Deletes a user from the database.
     *
     * This method removes the user record with the specified ID from
     * the database. If no user exists with the given ID, a
     * [NoResultsFoundException] is thrown.
     *
     * @param userId The unique identifier of the user to delete
     * @return Mono containing the deleted user
     * @throws NoResultsFoundException if no user exists with the given ID
     */
    fun deleteUser(userId: Int): Mono<User> {
        logger.debug("Deleting user: {}", userId)
        return postgresClient.update(
            "DELETE FROM \"user\" WHERE id=$1",
            userId,
        )
    }
}
