apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: congen

resources:
  - ../../../base/stage-5

patches:
- path: patches/migration-service-labels-patch.yaml
  target:
    kind: Deployment
    name: migration-service
