apiVersion: batch/v1
kind: Job
metadata:
  name: keycloak-migrations
spec:
  template:
    spec:
      initContainers:
      - name: wait-for-postgres
        image: mirror.gcr.io/busybox:1.35
        command: ['sh', '-c', 'timeout 180 sh -c "until nc -z postgres 5432; do echo waiting for postgres; sleep 2; done; echo postgres is ready;" || (echo "Timeout waiting for postgres"; exit 1)']
