apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: congen

resources:
- ../../../base/stage-4

patches:
- path: patches/congen-secret-patch.yaml
  target:
    kind: Secret
    name: congen-secret
