package com.congen.controllers

import com.congen.dal.ProgrammedWorkoutDAL
import com.congen.model.ProgrammedWorkout
import org.slf4j.LoggerFactory
import org.springframework.http.ResponseEntity
import org.springframework.web.bind.annotation.DeleteMapping
import org.springframework.web.bind.annotation.GetMapping
import org.springframework.web.bind.annotation.PatchMapping
import org.springframework.web.bind.annotation.PathVariable
import org.springframework.web.bind.annotation.PostMapping
import org.springframework.web.bind.annotation.RequestMapping
import org.springframework.web.bind.annotation.RequestParam
import org.springframework.web.bind.annotation.RestController
import reactor.core.publisher.Mono

/**
 * REST controller for ProgrammedWorkout entity operations.
 *
 * This controller provides CRUD operations for programmed workouts in the Congen API.
 * Programmed workouts represent specific workout sessions within a program, with
 * their own day number and associated workout stages.
 *
 * ## ProgrammedWorkout Entity
 *
 * A programmed workout represents a specific workout session within a program:
 * - Unique identifier and name
 * - Reference to the parent program
 * - Day number within the program
 * - Associated workout stages
 *
 * ## Endpoints
 *
 * - `POST /programmed-workout/` - Create a new programmed workout
 * - `GET /programmed-workout/{id}` - Retrieve a programmed workout by ID
 * - `GET /programmed-workout/` - Retrieve all programmed workouts
 * - `GET /programmed-workout/program/{programId}` - Get workouts for a specific program
 * - `PATCH /programmed-workout/` - Update an existing programmed workout
 * - `DELETE /programmed-workout/{id}` - Delete a programmed workout
 *
 * ## Error Handling
 *
 * - **404 Not Found**: When a programmed workout with the specified ID doesn't exist
 * - **422 Unprocessable Entity**: When validation fails
 * - **500 Internal Server Error**: When database operations fail
 *
 * @property programmedWorkoutDAL Data access layer for programmed workout operations
 *
 * @author Congen Development Team
 * @since 1.0.0
 */
@RestController
@RequestMapping("/programmed_workout")
class ProgrammedWorkoutController(
    private val programmedWorkoutDAL: ProgrammedWorkoutDAL,
) {
    companion object {
        /** Logger instance for this class. */
        private val logger = LoggerFactory.getLogger(ProgrammedWorkoutController::class.java)
    }

    /**
     * Creates a new programmed workout.
     *
     * This endpoint accepts programmed workout parameters and saves it to the database.
     * The programmed workout ID is automatically generated by the database. The method
     * returns the created programmed workout with the generated ID.
     *
     * @param programId The ID of the program this workout belongs to
     * @param dayNumber The day number within the program
     * @param name The name of the workout
     * @return Mono containing the created programmed workout with generated ID
     */
    @PostMapping("/")
    fun save(
        @RequestParam programId: Long,
        @RequestParam dayNumber: Int,
        @RequestParam name: String,
    ): Mono<ResponseEntity<ProgrammedWorkout>> {
        logger.info("Saving programmed workout: {} for program {}", name, programId)
        return programmedWorkoutDAL.insertProgrammedWorkout(programId, dayNumber, name)
            .map { savedWorkout ->
                logger.debug("Saved programmed workout with id: {}", savedWorkout.id)
                ResponseEntity.ok(savedWorkout)
            }
            .doOnError { e ->
                logger.error("Error saving programmed workout: {} for program {}", name, programId, e)
            }
    }

    /**
     * Retrieves a programmed workout by its unique identifier.
     *
     * This endpoint fetches a programmed workout from the database using the provided ID.
     * If no programmed workout exists with the given ID, an error response is returned.
     *
     * @param id The unique identifier of the programmed workout to retrieve
     * @return Mono containing the programmed workout if found
     */
    @GetMapping("/{id}")
    fun get(
        @PathVariable("id") id: Long,
    ): Mono<ResponseEntity<ProgrammedWorkout>> {
        return programmedWorkoutDAL.selectProgrammedWorkoutById(id)
            .map {
                logger.debug("Found programmed workout: {}", id)
                ResponseEntity.ok(it)
            }
            .onErrorResume { e ->
                logger.warn("Programmed workout not found: {}", id)
                Mono.just(ResponseEntity.notFound().build())
            }
            .doOnError { e ->
                logger.error("Error getting programmed workout: {}", id, e)
            }
    }

    /**
     * Retrieves all programmed workouts from the database.
     *
     * This endpoint fetches all programmed workout records and returns them as a list.
     * If no programmed workouts exist, an empty list is returned.
     *
     * @return ResponseEntity containing a list of all programmed workouts
     */
    @GetMapping("/")
    fun getAll(): ResponseEntity<*> {
        logger.debug("Getting all programmed workouts")
        return try {
            ResponseEntity.ok(
                programmedWorkoutDAL.selectProgrammedWorkouts(),
            )
        } catch (e: Exception) {
            logger.error("Error getting all programmed workouts", e)
            throw e
        }
    }

    /**
     * Retrieves all programmed workouts for a specific program.
     *
     * This endpoint fetches all programmed workouts that belong to a specific
     * program, ordered by their day number within the program.
     *
     * @param programId The unique identifier of the program
     * @return ResponseEntity containing a list of programmed workouts for the program
     */
    @GetMapping("/program/{programId}")
    fun getByProgramId(
        @PathVariable("programId") programId: Long,
    ): ResponseEntity<*> {
        logger.debug("Getting programmed workouts for program: {}", programId)
        return try {
            ResponseEntity.ok(
                programmedWorkoutDAL.selectProgrammedWorkoutsByProgramId(programId),
            )
        } catch (e: Exception) {
            logger.error("Error getting programmed workouts for program: {}", programId, e)
            throw e
        }
    }

    /**
     * Updates an existing programmed workout.
     *
     * This endpoint updates a programmed workout using the provided parameters.
     * The programmed workout ID from the path parameter is used to identify which workout
     * to update.
     *
     * @param id The unique identifier of the programmed workout to update
     * @param programId The updated program ID
     * @param dayNumber The updated day number within the program
     * @param name The updated name of the workout
     * @return ResponseEntity containing the updated programmed workout
     */
    @PatchMapping("/{id}")
    fun update(
        @PathVariable("id") id: Long,
        @RequestParam programId: Long,
        @RequestParam dayNumber: Int,
        @RequestParam name: String,
    ): Mono<ResponseEntity<ProgrammedWorkout>> {
        return programmedWorkoutDAL.updateProgrammedWorkout(id, programId, dayNumber, name)
            .map {
                logger.debug("Updated programmed workout: {}", id)
                ResponseEntity.ok(it)
            }
            .onErrorResume { e ->
                logger.warn("Programmed workout not found for update: {}", id)
                Mono.just(ResponseEntity.notFound().build())
            }
            .doOnError { e ->
                logger.error("Error updating programmed workout: {}", id, e)
            }
    }

    /**
     * Deletes a programmed workout by its unique identifier.
     *
     * This endpoint removes a programmed workout from the database using the provided ID.
     * The method returns the deleted programmed workout data for confirmation.
     *
     * @param id The unique identifier of the programmed workout to delete
     * @return ResponseEntity containing the deleted programmed workout
     */
    @DeleteMapping("/{id}")
    fun delete(
        @PathVariable("id") id: Long,
    ): Mono<ResponseEntity<ProgrammedWorkout>> {
        return programmedWorkoutDAL.deleteProgrammedWorkout(id)
            .map {
                logger.debug("Deleted programmed workout: {}", id)
                ResponseEntity.ok(it)
            }
            .onErrorResume { e ->
                logger.warn("Programmed workout not found for deletion: {}", id)
                Mono.just(ResponseEntity.notFound().build())
            }
            .doOnError { e ->
                logger.error("Error deleting programmed workout: {}", id, e)
            }
    }
}
