package com.congen.controllers

import com.congen.dal.ProgramDAL
import com.congen.exceptions.NoResultsFoundException
import com.congen.model.Program
import org.slf4j.LoggerFactory
import org.springframework.http.ResponseEntity
import org.springframework.web.bind.annotation.DeleteMapping
import org.springframework.web.bind.annotation.GetMapping
import org.springframework.web.bind.annotation.PatchMapping
import org.springframework.web.bind.annotation.PathVariable
import org.springframework.web.bind.annotation.PostMapping
import org.springframework.web.bind.annotation.RequestBody
import org.springframework.web.bind.annotation.RequestMapping
import org.springframework.web.bind.annotation.RequestParam
import org.springframework.web.bind.annotation.RestController
import reactor.core.publisher.Mono

/**
 * REST controller for Program entity operations.
 *
 * This controller provides CRUD operations for workout programs in the Congen API.
 * Programs represent structured workout plans that can be assigned to users and
 * contain multiple programmed workouts.
 *
 * ## Program Entity
 *
 * A program represents a complete workout plan with:
 * - Unique identifier and name
 * - Description of the program
 * - Associated programmed workouts
 * - User assignments and preferences
 *
 * ## Endpoints
 *
 * - `POST /program/` - Create a new program
 * - `GET /program/{id}` - Retrieve a program by ID
 * - `GET /program/` - Retrieve all programs
 * - `PATCH /program/{id}` - Update an existing program
 * - `DELETE /program/{id}` - Delete a program
 *
 * ## Error Handling
 *
 * - **404 Not Found**: When a program with the specified ID doesn't exist
 * - **422 Unprocessable Entity**: When validation fails
 * - **500 Internal Server Error**: When database operations fail
 *
 * @property programDAL Data access layer for program operations
 *
 * @author Congen Development Team
 * @since 1.0.0
 */
@RestController
@RequestMapping("/program")
class ProgramController(
    private val programDAL: ProgramDAL,
) {
    companion object {
        /** Logger instance for this class. */
        private val logger = LoggerFactory.getLogger(ProgramController::class.java)
    }

    /**
     * Creates a new program.
     *
     * This endpoint accepts program parameters and saves it to the database.
     * The program ID is automatically generated by the database. The method
     * returns the created program with the generated ID.
     *
     * @param userId The user ID for the program
     * @param name The name of the program
     * @param description The description of the program
     * @return Mono containing the created program with generated ID
     */
    @PostMapping("/")
    fun save(
        @RequestParam userId: Int,
        @RequestParam name: String,
        @RequestParam description: String?,
    ): Mono<ResponseEntity<Program>> {
        logger.info("Saving program: {} for user {}", name, userId)
        return programDAL.insertProgram(userId, name, description)
            .map { savedProgram ->
                logger.debug("Saved program with id: {}", savedProgram.id)
                ResponseEntity.ok(savedProgram)
            }
            .doOnError { e ->
                logger.error("Error saving program: {} for user {}", name, userId, e)
            }
    }

    /**
     * Retrieves a program by its unique identifier.
     *
     * This endpoint fetches a program from the database using the provided ID.
     * If no program exists with the given ID, a 404 Not Found response is returned.
     *
     * @param id The unique identifier of the program to retrieve
     * @return Mono containing the program if found, or 404 if not found
     */
    @GetMapping("/{id}")
    fun get(
        @PathVariable("id") id: Long,
    ): Mono<ResponseEntity<Program>> {
        return programDAL.selectProgramById(id)
            .map {
                logger.debug("Found program: {}", id)
                ResponseEntity.ok(it)
            }
            .onErrorResume(NoResultsFoundException::class.java) {
                logger.warn("Program not found: {}", id)
                Mono.just(ResponseEntity.notFound().build())
            }
            .doOnError { e ->
                logger.error("Error getting program: {}", id, e)
            }
    }

    /**
     * Retrieves all programs from the database.
     *
     * This endpoint fetches all program records and returns them as a list.
     * If no programs exist, an empty list is returned.
     *
     * @return ResponseEntity containing a list of all programs
     */
    @GetMapping("/")
    fun getAll(): ResponseEntity<*> {
        logger.debug("Getting all programs")
        return try {
            ResponseEntity.ok(
                programDAL.selectPrograms(),
            )
        } catch (e: Exception) {
            logger.error("Error getting all programs", e)
            throw e
        }
    }

    /**
     * Updates an existing program.
     *
     * This endpoint updates a program with the specified ID using the provided
     * parameters. The ID from the path parameter is used to ensure the correct
     * program is updated. If no program exists with the given ID, a 404 Not Found
     * response is returned.
     *
     * @param id The unique identifier of the program to update
     * @param name The updated name of the program
     * @param description The updated description of the program
     * @return Mono containing the updated program, or 404 if not found
     */
    @PatchMapping("/{id}")
    fun update(
        @PathVariable("id") id: Long,
        @RequestParam name: String,
        @RequestParam description: String?,
    ): Mono<ResponseEntity<Program>> {
        return programDAL.updateProgram(id, name, description)
            .map {
                logger.debug("Updated program: {}", id)
                ResponseEntity.ok(it)
            }
            .onErrorResume(NoResultsFoundException::class.java) {
                logger.warn("Program not found for update: {}", id)
                Mono.just(ResponseEntity.notFound().build())
            }
            .doOnError { e ->
                logger.error("Error updating program: {}", id, e)
            }
    }

    /**
     * Deletes a program by its unique identifier.
     *
     * This endpoint removes a program from the database using the provided ID.
     * If no program exists with the given ID, a 404 Not Found response is returned.
     * The method returns the deleted program data for confirmation.
     *
     * @param id The unique identifier of the program to delete
     * @return Mono containing the deleted program, or 404 if not found
     */
    @DeleteMapping("/{id}")
    fun delete(
        @PathVariable("id") id: Long,
    ): Mono<ResponseEntity<Program>> {
        return programDAL.deleteProgram(id)
            .map {
                logger.debug("Deleted program: {}", id)
                ResponseEntity.ok(it)
            }
            .onErrorResume(NoResultsFoundException::class.java) {
                logger.warn("Program not found for deletion: {}", id)
                Mono.just(ResponseEntity.notFound().build())
            }
            .doOnError { e ->
                logger.error("Error deleting program: {}", id, e)
            }
    }
}
