package com.congen.controllers

import com.congen.dal.ProgrammedExerciseDAL
import com.congen.exceptions.NoResultsFoundException
import com.congen.model.ProgrammedExercise
import org.slf4j.LoggerFactory
import org.springframework.http.ResponseEntity
import org.springframework.web.bind.annotation.DeleteMapping
import org.springframework.web.bind.annotation.GetMapping
import org.springframework.web.bind.annotation.PatchMapping
import org.springframework.web.bind.annotation.PathVariable
import org.springframework.web.bind.annotation.PostMapping
import org.springframework.web.bind.annotation.RequestMapping
import org.springframework.web.bind.annotation.RequestParam
import org.springframework.web.bind.annotation.RestController
import reactor.core.publisher.Mono

/**
 * REST controller for ProgrammedExercise entity operations.
 *
 * This controller provides CRUD operations for programmed exercises in the Congen API.
 * Programmed exercises represent specific exercises that are assigned to workout stages
 * within a programmed workout, with their own configuration and set schemes.
 *
 * ## ProgrammedExercise Entity
 *
 * A programmed exercise represents an exercise within a workout stage:
 * - Unique identifier and position within the stage
 * - Reference to the parent workout stage
 * - Exercise name and configuration
 * - Associated set schemes for the exercise
 *
 * ## Endpoints
 *
 * - `POST /programmed_exercise/` - Create a new programmed exercise
 * - `GET /programmed_exercise/{id}` - Retrieve a programmed exercise by ID
 * - `GET /programmed_exercise/stage/{workoutStageId}` - Get exercises for a specific stage
 * - `GET /programmed_exercise/` - Retrieve all programmed exercises
 * - `PATCH /programmed_exercise/{id}` - Update an existing programmed exercise
 * - `DELETE /programmed_exercise/{id}` - Delete a programmed exercise
 *
 * ## Error Handling
 *
 * - **404 Not Found**: When a programmed exercise with the specified ID doesn't exist
 * - **422 Unprocessable Entity**: When validation fails
 * - **500 Internal Server Error**: When database operations fail
 *
 * @property programmedExerciseDAL Data access layer for programmed exercise operations
 *
 * @author Congen Development Team
 * @since 1.0.0
 */
@RestController
@RequestMapping("/programmed_exercise")
class ProgrammedExerciseController(
    private val programmedExerciseDAL: ProgrammedExerciseDAL,
) {
    companion object {
        /** Logger instance for this class. */
        private val logger = LoggerFactory.getLogger(ProgrammedExerciseController::class.java)
    }

    /**
     * Creates a new programmed exercise.
     *
     * This endpoint accepts programmed exercise parameters and saves it to the database.
     * The programmed exercise ID is automatically generated by the database. The method
     * returns the created programmed exercise with the generated ID.
     *
     * @param workoutStageId The ID of the workout stage this exercise belongs to
     * @param exerciseName The name of the exercise to be performed
     * @param position The position of this exercise within the stage
     * @param notes Optional notes or instructions for the exercise
     * @return Mono containing the created programmed exercise with generated ID
     */
    @PostMapping("/")
    fun save(
        @RequestParam workoutStageId: Long,
        @RequestParam exerciseName: String,
        @RequestParam position: Int,
        @RequestParam notes: String?,
    ): Mono<ResponseEntity<ProgrammedExercise>> {
        logger.info("Saving programmed exercise: {} for stage: {} at position: {}", exerciseName, workoutStageId, position)
        return programmedExerciseDAL.insertProgrammedExercise(workoutStageId, exerciseName, position, notes)
            .map { savedExercise ->
                logger.debug("Saved programmed exercise with id: {}", savedExercise.id)
                ResponseEntity.ok(savedExercise)
            }
            .doOnError { e ->
                logger.error(
                    "Error saving programmed exercise: {} for stage: {} at position: {}",
                    exerciseName,
                    workoutStageId,
                    position,
                    e,
                )
            }
    }

    /**
     * Retrieves a programmed exercise by its unique identifier.
     *
     * This endpoint fetches a programmed exercise from the database using the provided ID.
     * If no programmed exercise exists with the given ID, a 404 Not Found response is returned.
     *
     * @param id The unique identifier of the programmed exercise to retrieve
     * @return Mono containing the programmed exercise if found, or 404 if not found
     */
    @GetMapping("/{id}")
    fun get(
        @PathVariable("id") id: Long,
    ): Mono<ResponseEntity<ProgrammedExercise>> {
        return programmedExerciseDAL.selectProgrammedExerciseById(id)
            .map {
                logger.debug("Found programmed exercise: {}", id)
                ResponseEntity.ok(it)
            }
            .onErrorResume(NoResultsFoundException::class.java) {
                logger.warn("Programmed exercise not found: {}", id)
                Mono.just(ResponseEntity.notFound().build())
            }
            .doOnError { e ->
                logger.error("Error getting programmed exercise: {}", id, e)
            }
    }

    /**
     * Retrieves all programmed exercises for a specific workout stage.
     *
     * This endpoint fetches all programmed exercises that belong to a specific
     * workout stage, ordered by their position within the stage.
     *
     * @param workoutStageId The unique identifier of the workout stage
     * @return ResponseEntity containing a list of programmed exercises for the stage
     */
    @GetMapping("/stage/{workoutStageId}")
    fun getByStage(
        @PathVariable("workoutStageId") workoutStageId: Long,
    ): ResponseEntity<*> {
        logger.debug("Getting programmed exercises for stage: {}", workoutStageId)
        return try {
            ResponseEntity.ok(
                programmedExerciseDAL.selectProgrammedExercisesByWorkoutStageId(workoutStageId),
            )
        } catch (e: Exception) {
            logger.error("Error getting programmed exercises for stage: {}", workoutStageId, e)
            throw e
        }
    }

    /**
     * Retrieves all programmed exercises from the database.
     *
     * This endpoint fetches all programmed exercise records and returns them as a list.
     * If no programmed exercises exist, an empty list is returned.
     *
     * @return ResponseEntity containing a list of all programmed exercises
     */
    @GetMapping("/")
    fun getAll(): ResponseEntity<*> {
        logger.debug("Getting all programmed exercises")
        return try {
            ResponseEntity.ok(
                programmedExerciseDAL.selectProgrammedExercises(),
            )
        } catch (e: Exception) {
            logger.error("Error getting all programmed exercises", e)
            throw e
        }
    }

    /**
     * Updates an existing programmed exercise.
     *
     * This endpoint updates a programmed exercise with the specified ID using the provided
     * parameters. The ID from the path parameter is used to ensure the correct
     * programmed exercise is updated. If no programmed exercise exists with the given ID,
     * a 404 Not Found response is returned.
     *
     * @param id The unique identifier of the programmed exercise to update
     * @param workoutStageId The updated workout stage ID
     * @param exerciseName The updated exercise name
     * @param position The updated position of this exercise within the stage
     * @param notes The updated notes or instructions
     * @return Mono containing the updated programmed exercise, or 404 if not found
     */
    @PatchMapping("/{id}")
    fun update(
        @PathVariable("id") id: Long,
        @RequestParam workoutStageId: Long,
        @RequestParam exerciseName: String,
        @RequestParam position: Int,
        @RequestParam notes: String?,
    ): Mono<ResponseEntity<ProgrammedExercise>> {
        return programmedExerciseDAL.updateProgrammedExercise(id, workoutStageId, exerciseName, position, notes)
            .map {
                logger.debug("Updated programmed exercise: {}", id)
                ResponseEntity.ok(it)
            }
            .onErrorResume(NoResultsFoundException::class.java) {
                logger.warn("Programmed exercise not found for update: {}", id)
                Mono.just(ResponseEntity.notFound().build())
            }
            .doOnError { e ->
                logger.error("Error updating programmed exercise: {}", id, e)
            }
    }

    /**
     * Deletes a programmed exercise by its unique identifier.
     *
     * This endpoint removes a programmed exercise from the database using the provided ID.
     * If no programmed exercise exists with the given ID, a 404 Not Found response is returned.
     * The method returns the deleted programmed exercise data for confirmation.
     *
     * @param id The unique identifier of the programmed exercise to delete
     * @return Mono containing the deleted programmed exercise, or 404 if not found
     */
    @DeleteMapping("/{id}")
    fun delete(
        @PathVariable("id") id: Long,
    ): Mono<ResponseEntity<ProgrammedExercise>> {
        return programmedExerciseDAL.deleteProgrammedExercise(id)
            .map {
                logger.debug("Deleted programmed exercise: {}", id)
                ResponseEntity.ok(it)
            }
            .onErrorResume(NoResultsFoundException::class.java) {
                logger.warn("Programmed exercise not found for deletion: {}", id)
                Mono.just(ResponseEntity.notFound().build())
            }
            .doOnError { e ->
                logger.error("Error deleting programmed exercise: {}", id, e)
            }
    }
}
