package com.congen.controllers

import com.congen.model.SetScheme
import com.congen.service.SetSchemeService
import org.slf4j.LoggerFactory
import org.springframework.http.ResponseEntity
import org.springframework.web.bind.annotation.DeleteMapping
import org.springframework.web.bind.annotation.GetMapping
import org.springframework.web.bind.annotation.PatchMapping
import org.springframework.web.bind.annotation.PathVariable
import org.springframework.web.bind.annotation.PostMapping
import org.springframework.web.bind.annotation.RequestBody
import org.springframework.web.bind.annotation.RequestMapping
import org.springframework.web.bind.annotation.RestController
import reactor.core.publisher.Mono

/**
 * REST controller for SetScheme entity operations.
 *
 * This controller provides CRUD operations for set schemes in the Congen API.
 * Set schemes define the specific parameters for individual sets within a
 * programmed exercise, including weight, reps, tempo, and rest periods.
 *
 * ## SetScheme Entity
 *
 * A set scheme represents the configuration for a specific set within an exercise:
 * - Unique identifier and set number within the exercise
 * - Reference to the parent programmed exercise
 * - Target and performed weight, reps, and tempo
 * - Rest period and completion status
 *
 * ## Endpoints
 *
 * - `POST /set-schemes/` - Create a new set scheme
 * - `GET /set-schemes/{id}` - Retrieve a set scheme by ID
 * - `GET /set-schemes/` - Retrieve all set schemes
 * - `GET /set-schemes/exercise/{programmedExerciseId}` - Get schemes for a specific exercise
 * - `PATCH /set-schemes/` - Update an existing set scheme
 * - `DELETE /set-schemes/{id}` - Delete a set scheme
 *
 * ## Error Handling
 *
 * - **404 Not Found**: When a set scheme with the specified ID doesn't exist
 * - **422 Unprocessable Entity**: When validation fails
 * - **500 Internal Server Error**: When database operations fail
 *
 * @property setSchemeService Service layer for set scheme operations
 *
 * @author Congen Development Team
 * @since 1.0.0
 */
@RestController
@RequestMapping("/set-schemes")
class SetSchemeController(
    private val setSchemeService: SetSchemeService,
) {
    companion object {
        /** Logger instance for this class. */
        private val logger = LoggerFactory.getLogger(SetSchemeController::class.java)
    }

    /**
     * Creates a new set scheme.
     *
     * This endpoint accepts a set scheme object and saves it to the database.
     * The set scheme ID is automatically generated by the database. The method
     * returns the created set scheme with the generated ID.
     *
     * @param setScheme The set scheme object to create
     * @return Mono containing the created set scheme with generated ID
     */
    @PostMapping("/")
    fun save(
        @RequestBody setScheme: SetScheme,
    ): Mono<ResponseEntity<SetScheme>> {
        logger.info("Saving set scheme for exercise: {}, set: {}", setScheme.programmedExerciseId, setScheme.setNumber)
        return setSchemeService.insertSetScheme(setScheme)
            .map { savedScheme ->
                logger.debug("Saved set scheme with id: {}", savedScheme.id)
                ResponseEntity.ok(savedScheme)
            }
            .doOnError { e ->
                logger.error("Error saving set scheme for exercise: {}, set: {}", setScheme.programmedExerciseId, setScheme.setNumber, e)
            }
    }

    /**
     * Retrieves a set scheme by its unique identifier.
     *
     * This endpoint fetches a set scheme from the database using the provided ID.
     * If no set scheme exists with the given ID, an error response is returned.
     *
     * @param id The unique identifier of the set scheme to retrieve
     * @return Mono containing the set scheme if found
     */
    @GetMapping("/{id}")
    fun get(
        @PathVariable("id") id: Long,
    ): Mono<ResponseEntity<SetScheme>> {
        return setSchemeService.selectSetSchemeById(id)
            .map { setScheme ->
                logger.debug("Found set scheme: {}", id)
                ResponseEntity.ok(setScheme)
            }
            .doOnError { e ->
                logger.error("Error getting set scheme: {}", id, e)
            }
    }

    /**
     * Retrieves all set schemes from the database.
     *
     * This endpoint fetches all set scheme records and returns them as a list.
     * If no set schemes exist, an empty list is returned.
     *
     * @return ResponseEntity containing a list of all set schemes
     */
    @GetMapping("/")
    fun getAll(): ResponseEntity<*> {
        logger.debug("Getting all set schemes")
        return try {
            ResponseEntity.ok(
                setSchemeService.selectSetSchemes(),
            )
        } catch (e: Exception) {
            logger.error("Error getting all set schemes", e)
            throw e
        }
    }

    /**
     * Retrieves all set schemes for a specific programmed exercise.
     *
     * This endpoint fetches all set schemes that belong to a specific
     * programmed exercise, ordered by their set number within the exercise.
     *
     * @param programmedExerciseId The unique identifier of the programmed exercise
     * @return ResponseEntity containing a list of set schemes for the exercise
     */
    @GetMapping("/exercise/{programmedExerciseId}")
    fun getByProgrammedExerciseId(
        @PathVariable("programmedExerciseId") programmedExerciseId: Long,
    ): ResponseEntity<*> {
        logger.debug("Getting set schemes for programmed exercise: {}", programmedExerciseId)
        return try {
            ResponseEntity.ok(
                setSchemeService.selectSetSchemesByProgrammedExerciseId(programmedExerciseId),
            )
        } catch (e: Exception) {
            logger.error("Error getting set schemes for programmed exercise: {}", programmedExerciseId, e)
            throw e
        }
    }

    /**
     * Updates an existing set scheme.
     *
     * This endpoint updates a set scheme using the provided set scheme data.
     * The set scheme ID from the request body is used to identify which scheme
     * to update.
     *
     * @param setScheme The set scheme object with updated data
     * @return ResponseEntity containing the updated set scheme
     */
    @PatchMapping("/")
    fun update(
        @RequestBody setScheme: SetScheme,
    ): ResponseEntity<*> {
        logger.info("Updating set scheme: {}", setScheme.id)
        return try {
            ResponseEntity.ok(
                setSchemeService.updateSetScheme(setScheme),
            )
        } catch (e: Exception) {
            logger.error("Error updating set scheme: {}", setScheme.id, e)
            throw e
        }
    }

    /**
     * Deletes a set scheme by its unique identifier.
     *
     * This endpoint removes a set scheme from the database using the provided ID.
     * The method returns the deleted set scheme data for confirmation.
     *
     * @param id The unique identifier of the set scheme to delete
     * @return ResponseEntity containing the deleted set scheme
     */
    @DeleteMapping("/{id}")
    fun delete(
        @PathVariable("id") id: Long,
    ): ResponseEntity<*> {
        logger.info("Deleting set scheme: {}", id)
        return try {
            ResponseEntity.ok(
                setSchemeService.deleteSetScheme(id),
            )
        } catch (e: Exception) {
            logger.error("Error deleting set scheme: {}", id, e)
            throw e
        }
    }
}
