package com.congen.model

import com.fasterxml.jackson.annotation.JsonIgnoreProperties
import com.fasterxml.jackson.annotation.JsonProperty
import com.fasterxml.jackson.databind.PropertyNamingStrategies
import com.fasterxml.jackson.databind.annotation.JsonNaming
import io.swagger.v3.oas.annotations.media.Schema
import java.time.Instant

/**
 * GDPR audit log entry for tracking user data operations.
 *
 * This class represents an audit log entry that records various operations performed on user data
 * for GDPR compliance purposes. It tracks who performed what operation on which type of data
 * and when it occurred.
 */
@JsonNaming(PropertyNamingStrategies.SnakeCaseStrategy::class)
@JsonIgnoreProperties(ignoreUnknown = true)
@Schema(description = "GDPR audit log entry")
data class AuditLog(
    /**
     * Unique identifier for the audit log entry.
     *
     * This field is auto-generated by the database and may be null for new entries.
     */
    @Schema(description = "Unique identifier for the audit log entry")
    @param:JsonProperty("id") val id: Long? = null,
    /**
     * Keycloak ID of the user associated with the audit event.
     *
     * This field may be null for system operations that don't involve a specific user.
     */
    @Schema(description = "Keycloak ID of the user associated with the audit event (null for system operations)")
    @param:JsonProperty("keycloak_id") val keycloakId: String?,
    /**
     * Type of operation performed on the data.
     *
     * Examples include: CREATE, READ, UPDATE, DELETE, EXPORT, etc.
     */
    @Schema(description = "Type of operation performed")
    @param:JsonProperty("operation") val operation: String,
    /**
     * Type of data affected by the operation.
     *
     * Examples include: USER_PROFILE, EXERCISE_DATA, WORKOUT_HISTORY, etc.
     */
    @Schema(description = "Type of data affected by the operation")
    @param:JsonProperty("data_type") val dataType: String,
    /**
     * ID of the user who performed the operation.
     *
     * This field may be null for system operations that are performed automatically.
     */
    @Schema(description = "ID of the user who performed the operation (null for system operations)")
    @param:JsonProperty("performed_by") val performedBy: String?,
    /**
     * When the audit event occurred.
     *
     * This timestamp is automatically set when the audit log entry is created.
     */
    @Schema(description = "When the audit event occurred")
    @param:JsonProperty("timestamp") val timestamp: Instant,
    /**
     * Additional information about the audit event.
     *
     * This field can contain any additional context or details about the operation
     * that may be useful for compliance or debugging purposes.
     */
    @Schema(description = "Additional information about the audit event")
    @param:JsonProperty("additional_info") val additionalInfo: String? = null
)
