apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: congen-ingress
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    cert-manager.io/cluster-issuer: "letsencrypt-staging"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
spec:
  tls:
  - hosts:
    - staging.congen.com
    secretName: congen-staging-tls
  rules:
  - host: staging.congen.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: congen
            port:
              number: 8080 