#  The liquibase.properties file stores properties which do not change often,
#  such as database connection information. Properties stored here save time
#  and reduce risk of mistyped command line arguments.
#  Learn more: https://docs.liquibase.com/concepts/connections/creating-config-properties.html

# NOTE This is the path the file is mounted under, relative to the mounted location,
#      NOT relative to the current working directory where you are editing this file!
changelogFile: changelog-root.xml

# Disable because se need to be able to fetch the schemas for the changelog xml.
liquibase.secureParsing: false

# Enable property substitution for environment variables
liquibase.propertySubstitutionEnabled: true

# Logging Configuration
# logLevel controls the amount of logging information generated. If not set, the default logLevel is INFO.
# Valid values, from least amount of logging to most, are:
#   OFF, ERROR, WARN, INFO, DEBUG, TRACE, ALL
# If you are having problems, setting the logLevel to DEBUG and re-running the command can be helpful.
logLevel: INFO
