apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: congen

resources:
- ../../base/ingress.yaml

patches:
- path: patches/ingress-patch.yaml
  target:
    kind: Ingress
    name: congen-ingress 