#Generated version information
#Sat Aug 30 08:59:13 EDT 2025
app.releaseId=main-6ca5e7d458-local-1756558753247
app.gitHash=6ca5e7d458
app.buildTime=2025-08-30T08\:59\:13Z
app.gitDirty=true
app.gitBranch=main
app.version=0.0.1-SNAPSHOT
