apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: backend
data:
  SPRING_PROFILES_ACTIVE: "loc"
  CORS_ALLOWED_ORIGINS: "http://localhost:3000,http://localhost:8080"
  CORS_ALLOWED_METHODS: "GET,POST,PUT,DELETE,OPTIONS"
  CORS_ALLOWED_HEADERS: "Content-Type,Authorization,X-Requested-With"
  CORS_EXPOSED_HEADERS: "Content-Type,Content-Range"
  CORS_MAX_AGE: "86400"
  PGSSLMODE: "false"
  SPRINGDOC_API_DOCS_ENABLED: "false"
  SPRINGDOC_SWAGGER_UI_ENABLED: "false"
  SPRINGDOC_SWAGGER_UI_PATH: "/swagger-ui.html"
  SPRINGDOC_API_DOCS_PATH: "/api-docs"
  SPRINGDOC_SWAGGER_UI_OPERATIONS_SORTER: "method"
  SPRINGDOC_SWAGGER_UI_TAGS_SORTER: "alpha"
  SPRINGDOC_SWAGGER_UI_DOC_EXPANSION: "none"
  SPRINGDOC_SWAGGER_UI_DISPLAY_REQUEST_DURATION: "true"
  SPRINGDOC_SWAGGER_UI_FILTER: "true"
  KEYCLOAK_URL: "http://keycloak:8081"
  KEYCLOAK_REALM: "congen"
  KEYCLOAK_AUTH_URL: "http://keycloak:8081/auth/"
  KEYCLOAK_CLIENT_ID: "congen-backend" 