apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespace.yaml
- service-account.yaml
- reloader-rbac.yaml
- migrations-configmap.yaml
- migration-service-deployment.yaml
- reloader-deployment.yaml
- congen-configmap.yaml
- congen-deployment.yaml
- congen-service.yaml
- frontend-deployment.yaml
- frontend-service.yaml
- ingress.yaml
- network-policy.yaml 
- keycloak-deployment.yaml
- keycloak-service.yaml 