apiVersion: v1
kind: ConfigMap
metadata:
  name: congen-config
data:
  SPRINGDOC_API_DOCS_ENABLED: "true"
  SPRINGDOC_SWAGGER_UI_ENABLED: "true"
  SPRINGDOC_SWAGGER_UI_PATH: "/swagger-ui.html"
  SPRINGDOC_API_DOCS_PATH: "/api-docs"
  SPRINGDOC_SWAGGER_UI_OPERATIONS_SORTER: "method"
  SPRINGDOC_SWAGGER_UI_TAGS_SORTER: "alpha"
  SPRINGDOC_SWAGGER_UI_DOC_EXPANSION: "none"
  SPRINGDOC_SWAGGER_UI_DISPLAY_REQUEST_DURATION: "true"
  SPRINGDOC_SWAGGER_UI_FILTER: "true" 