apiVersion: apps/v1
kind: Deployment
metadata:
  name: congen
spec:
  template:
    spec:
      containers:
      - name: congen
        imagePullPolicy: Never
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "250m" 