apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: congen

resources:
- ../../base
- staging-secret.yaml

patches:
- path: staging-patches/congen-configmap-patch.yaml
  target:
    kind: ConfigMap
    name: congen-config
- path: staging-patches/congen-deployment-patch.yaml
  target:
    kind: Deployment
    name: congen
- path: staging-patches/congen-service-patch.yaml
  target:
    kind: Service
    name: congen
- path: staging-patches/ingress-patch.yaml
  target:
    kind: Ingress
    name: congen-ingress
- path: staging-patches/liquibase-job-labels-patch.yaml
  target:
    kind: Job
    name: liquibase-migration 